
# To learn more about how to define values in TOML, see https://toml.io/en/v1.0.0

# The "io" table lists I/O endpoints and corresponding actions that should be taken for each.
[io]
"file:/dev/null" = "nullsink" # Consume all input, produce repeating 0s
"stdio" = "fuzz" # Fuzz this endpoint

