
# To learn more about how to define values in TOML, see https://toml.io/en/v1.0.0

#[fizzle]
#max_fds = "100" # TODO: implement this in the future with build.rs

# The "io" table lists I/O endpoints and corresponding actions that should be taken for each.
[io]
"sctp-client:127.0.0.2:36412" = "fuzz"
# stdio = "fuzz" # Consume all input, produce fuzzing data as output
"file:/dev/null" = "nullsink" # Consume all input, produce repeating 0s
#"file:./myconfig" = "feedback" # Output whatever is given as input
#"udp-server:127.0.0.1:53" = "passthrough" # Pass on to an actual network service (warning: unstable)

#[io."sctp-server:127.0.0.1:38412"]
#method = "plugin" # The means of passing I/O on the device
#module = "fizzle-ngap" # The name of the cargo crate to source the plugin from
#plugin = "NgapServer" # The name of the `FizzlePlugin` implementation to be used

#[io."tcp-client:127.0.0.1:80"]
#method = "plugin" # The means of passing I/O on the device
#module = "fizzle-http" # The name of the cargo crate to source the plugin from
#plugin = "HttpClient" # The name of the `FizzlePlugin` implementation to be used
#streams = 5 # Establishes 5 client connections with the given server.

#[io."tcp-client:127.0.0.1:80".config]

#[io."tcp-client:127.0.0.1:8080"]
#method = "plugin" # The means of passing I/O on the device
#module = "fizzle-http" # The name of the cargo crate to source the plugin from
#plugin = "HttpClient" # The name of the `FizzlePlugin` implementation to be used
#streams = 1 # Establishes 5 client connections with the given server.

#[io."tcp-client:127.0.0.1:8080".config]
# Arbitrary configuration options specific to `fizzle-http` go here
# This configuration is passed
