// This code is auto-generated by the async-unsafe Python script in the fizzle-paper repository

use std::ffi::CStr;

use crate::hook_macros;

hook_macros::hook! {
    unsafe fn addmntent(
        _stream: *mut libc::c_void,
        _mnt: *mut libc::c_void
    ) -> libc::c_int => fizzle_addmntent(ctx) {

        hook_macros::real!(addmntent)(_stream, _mnt)
    }
}
    
hook_macros::hook! {
    unsafe fn addseverity(
        _severity: libc::c_int,
        _string: *mut libc::c_void
    ) -> libc::c_int => fizzle_addseverity(ctx) {

        hook_macros::real!(addseverity)(_severity, _string)
    }
}
    
hook_macros::hook! {
    unsafe fn aio_cancel64(
        _fildes: libc::c_int,
        _aiocbp: *mut libc::c_void
    ) -> libc::c_int => fizzle_aio_cancel64(ctx) {

        hook_macros::real!(aio_cancel64)(_fildes, _aiocbp)
    }
}
    
hook_macros::hook! {
    unsafe fn aio_fsync64(
        _op: libc::c_int,
        _aiocbp: *mut libc::c_void
    ) -> libc::c_int => fizzle_aio_fsync64(ctx) {

        hook_macros::real!(aio_fsync64)(_op, _aiocbp)
    }
}
    
hook_macros::hook! {
    unsafe fn aio_init(
        _init: *mut libc::c_void
    ) => fizzle_aio_init(ctx) {

        hook_macros::real!(aio_init)(_init)
    }
}
    
hook_macros::hook! {
    unsafe fn aio_read64(
        _aiocbp: *mut libc::c_void
    ) -> libc::c_int => fizzle_aio_read64(ctx) {

        hook_macros::real!(aio_read64)(_aiocbp)
    }
}
    
hook_macros::hook! {
    unsafe fn aio_suspend64(
        _list: *mut libc::c_void,
        _nent: libc::c_int,
        _timeout: *mut libc::c_void
    ) -> libc::c_int => fizzle_aio_suspend64(ctx) {

        hook_macros::real!(aio_suspend64)(_list, _nent, _timeout)
    }
}
    
hook_macros::hook! {
    unsafe fn aio_write64(
        _aiocbp: *mut libc::c_void
    ) -> libc::c_int => fizzle_aio_write64(ctx) {

        hook_macros::real!(aio_write64)(_aiocbp)
    }
}
    
hook_macros::hook! {
    unsafe fn aligned_alloc(
        _alignment: libc::size_t,
        _size: libc::size_t
    ) -> *mut libc::c_void => fizzle_aligned_alloc(ctx) {

        hook_macros::real!(aligned_alloc)(_alignment, _size)
    }
}
    
hook_macros::hook! {
    unsafe fn alphasort(
        _a: *mut *mut libc::c_void,
        _b: *mut *mut libc::c_void
    ) -> libc::c_int => fizzle_alphasort(ctx) {

        hook_macros::real!(alphasort)(_a, _b)
    }
}
    
hook_macros::hook! {
    unsafe fn alphasort64(
        _a: *mut *mut libc::c_void,
        _b: *mut *mut libc::c_void
    ) -> libc::c_int => fizzle_alphasort64(ctx) {

        hook_macros::real!(alphasort64)(_a, _b)
    }
}
    
#[unsafe(no_mangle)]
pub unsafe extern "C" fn argp_error(
        _state: *mut libc::c_void,
        _fmt: *mut libc::c_void,
        _va_args: ...
    ) {
    let Some(_ctx) = crate::hooks::pre_hook() else {
        panic!("argp_error() called internally by fizzle");
    };


    panic!("argp_error() called by program");
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn argp_failure(
        _state: *mut libc::c_void,
        _status: libc::c_int,
        _errnum: libc::c_int,
        _fmt: *mut libc::c_void,
        _va_args: ...
    )  {
    let Some(_ctx) = crate::hooks::pre_hook() else {
        panic!("argp_failure() called internally by fizzle");
    };


    panic!("argp_failure() called by program");
}

hook_macros::hook! {
    unsafe fn argp_help(
        _argp: *mut libc::c_void,
        _stream: *mut libc::c_void,
        _flags: libc::c_uint,
        _name: *mut libc::c_void
    ) => fizzle_argp_help(ctx) {

        hook_macros::real!(argp_help)(_argp, _stream, _flags, _name)
    }
}
    
hook_macros::hook! {
    unsafe fn argp_parse(
        _argp: *mut libc::c_void,
        _argc: libc::c_int,
        _argv: *mut *mut libc::c_void,
        _flags: libc::c_uint,
        _arg_index: *mut libc::c_void,
        _input: *mut libc::c_void
    ) -> libc::c_int => fizzle_argp_parse(ctx) {

        hook_macros::real!(argp_parse)(_argp, _argc, _argv, _flags, _arg_index, _input)
    }
}
    
hook_macros::hook! {
    unsafe fn argp_state_help(
        _state: *mut libc::c_void,
        _stream: *mut libc::c_void,
        _flags: libc::c_uint
    ) => fizzle_argp_state_help(ctx) {

        hook_macros::real!(argp_state_help)(_state, _stream, _flags)
    }
}
    
hook_macros::hook! {
    unsafe fn argp_usage(
        _state: *mut libc::c_void
    ) => fizzle_argp_usage(ctx) {

        hook_macros::real!(argp_usage)(_state)
    }
}
    
hook_macros::hook! {
    unsafe fn argz_add(
        _argz: *mut *mut libc::c_void,
        _argz_len: *mut libc::c_void,
        _str: *mut libc::c_void
    ) -> libc::c_int => fizzle_argz_add(ctx) {

        hook_macros::real!(argz_add)(_argz, _argz_len, _str)
    }
}
    
hook_macros::hook! {
    unsafe fn argz_add_sep(
        _argz: *mut *mut libc::c_void,
        _argz_len: *mut libc::c_void,
        _str: *mut libc::c_void,
        _delim: libc::c_int
    ) -> libc::c_int => fizzle_argz_add_sep(ctx) {

        hook_macros::real!(argz_add_sep)(_argz, _argz_len, _str, _delim)
    }
}
    
hook_macros::hook! {
    unsafe fn argz_append(
        _argz: *mut *mut libc::c_void,
        _argz_len: *mut libc::c_void,
        _buf: *mut libc::c_void,
        _buf_len: libc::size_t
    ) -> libc::c_int => fizzle_argz_append(ctx) {

        hook_macros::real!(argz_append)(_argz, _argz_len, _buf, _buf_len)
    }
}
    
hook_macros::hook! {
    unsafe fn argz_create(
        _argv: *mut libc::c_void,
        _argz: *mut *mut libc::c_void,
        _argz_len: *mut libc::c_void
    ) -> libc::c_int => fizzle_argz_create(ctx) {

        hook_macros::real!(argz_create)(_argv, _argz, _argz_len)
    }
}
    
hook_macros::hook! {
    unsafe fn argz_create_sep(
        _string: *mut libc::c_void,
        _sep: libc::c_int,
        _argz: *mut *mut libc::c_void,
        _argz_len: *mut libc::c_void
    ) -> libc::c_int => fizzle_argz_create_sep(ctx) {

        hook_macros::real!(argz_create_sep)(_string, _sep, _argz, _argz_len)
    }
}
    
hook_macros::hook! {
    unsafe fn argz_delete(
        _argz: *mut *mut libc::c_void,
        _argz_len: *mut libc::c_void,
        _entry: *mut libc::c_void
    ) => fizzle_argz_delete(ctx) {

        hook_macros::real!(argz_delete)(_argz, _argz_len, _entry)
    }
}
    
hook_macros::hook! {
    unsafe fn argz_insert(
        _argz: *mut *mut libc::c_void,
        _argz_len: *mut libc::c_void,
        _before: *mut libc::c_void,
        _entry: *mut libc::c_void
    ) -> libc::c_int => fizzle_argz_insert(ctx) {

        hook_macros::real!(argz_insert)(_argz, _argz_len, _before, _entry)
    }
}
    
hook_macros::hook! {
    unsafe fn argz_replace(
        _argz: *mut *mut libc::c_void,
        _argz_len: *mut libc::c_void,
        _str: *mut libc::c_void,
        _with: *mut libc::c_void,
        _replace_count: *mut libc::c_void
    ) -> libc::c_int => fizzle_argz_replace(ctx) {

        hook_macros::real!(argz_replace)(_argz, _argz_len, _str, _with, _replace_count)
    }
}
    
hook_macros::hook! {
    unsafe fn asctime(
        _brokentime: *mut libc::c_void
    ) -> *mut libc::c_void => fizzle_asctime(ctx) {

        hook_macros::real!(asctime)(_brokentime)
    }
}
    
#[unsafe(no_mangle)]
pub unsafe extern "C" fn asprintf(
        ptr: *mut *mut i8,
        template: *const i8,
        mut va_args: ...
    ) -> libc::c_int  {
    let Some(_ctx) = crate::hooks::pre_hook() else {
        return vasprintf(ptr, template, va_args)
    };


    let res = vasprintf(ptr, template, va_args);
    crate::hooks::post_hook();
    res
}

hook_macros::hook! {
    unsafe fn assert(
        _expression: libc::c_int
    ) => fizzle_assert(ctx) {

        hook_macros::real!(assert)(_expression)
    }
}
    
hook_macros::hook! {
    unsafe fn assert_perror(
        _errnum: libc::c_int
    ) => fizzle_assert_perror(ctx) {

        hook_macros::real!(assert_perror)(_errnum)
    }
}
    
hook_macros::hook! {
    unsafe fn backtrace(
        _buffer: *mut *mut libc::c_void,
        _size: libc::c_int
    ) -> libc::c_int => fizzle_backtrace(ctx) {

        hook_macros::real!(backtrace)(_buffer, _size)
    }
}
    
hook_macros::hook! {
    unsafe fn backtrace_symbols(
        _buffer: *mut *mut libc::c_void,
        _size: libc::c_int
    ) -> *mut *mut libc::c_void => fizzle_backtrace_symbols(ctx) {

        hook_macros::real!(backtrace_symbols)(_buffer, _size)
    }
}
    
hook_macros::hook! {
    unsafe fn bind_textdomain_codeset(
        _domainname: *mut libc::c_void,
        _codeset: *mut libc::c_void
    ) -> *mut libc::c_void => fizzle_bind_textdomain_codeset(ctx) {

        hook_macros::real!(bind_textdomain_codeset)(_domainname, _codeset)
    }
}
    
hook_macros::hook! {
    unsafe fn bindtextdomain(
        _domainname: *mut libc::c_void,
        _dirname: *mut libc::c_void
    ) -> *mut libc::c_void => fizzle_bindtextdomain(ctx) {

        hook_macros::real!(bindtextdomain)(_domainname, _dirname)
    }
}
    
hook_macros::hook! {
    unsafe fn calloc(
        _count: libc::size_t,
        _eltsize: libc::size_t
    ) -> *mut libc::c_void => fizzle_calloc(ctx) {

        hook_macros::real!(calloc)(_count, _eltsize)
    }
}
    
hook_macros::hook! {
    unsafe fn canonicalize_file_name(
        _name: *mut libc::c_void
    ) -> *mut libc::c_void => fizzle_canonicalize_file_name(ctx) {

        hook_macros::real!(canonicalize_file_name)(_name)
    }
}
    
hook_macros::hook! {
    unsafe fn catclose(
        _catalog_desc: libc::nl_item
    ) -> libc::c_int => fizzle_catclose(ctx) {

        hook_macros::real!(catclose)(_catalog_desc)
    }
}
    
hook_macros::hook! {
    unsafe fn catopen(
        _cat_name: *mut libc::c_void,
        _flag: libc::c_int
    ) -> libc::nl_item => fizzle_catopen(ctx) {

        hook_macros::real!(catopen)(_cat_name, _flag)
    }
}
    
hook_macros::hook! {
    unsafe fn clearenv() -> libc::c_int => fizzle_clearenv(ctx) {

        hook_macros::real!(clearenv)()
    }
}
    
hook_macros::hook! {
    unsafe fn cnd_timedwait(
        _cond: *mut libc::c_void,
        _mutex: *mut libc::c_void,
        _time_point: *mut libc::c_void
    ) -> libc::c_int => fizzle_cnd_timedwait(ctx) {

        hook_macros::real!(cnd_timedwait)(_cond, _mutex, _time_point)
    }
}
    
hook_macros::hook! {
    unsafe fn cnd_wait(
        _cond: *mut libc::c_void,
        _mutex: *mut libc::c_void
    ) -> libc::c_int => fizzle_cnd_wait(ctx) {

        hook_macros::real!(cnd_wait)(_cond, _mutex)
    }
}
    
hook_macros::hook! {
    unsafe fn ctime(
        _time: *mut libc::c_void
    ) -> *mut libc::c_void => fizzle_ctime(ctx) {

        hook_macros::real!(ctime)(_time)
    }
}
    
hook_macros::hook! {
    unsafe fn ctime_r(
        _time: *mut libc::c_void,
        _buffer: *mut libc::c_void
    ) -> *mut libc::c_void => fizzle_ctime_r(ctx) {

        hook_macros::real!(ctime_r)(_time, _buffer)
    }
}
    
hook_macros::hook! {
    unsafe fn cuserid(
        _string: *mut libc::c_void
    ) -> *mut libc::c_void => fizzle_cuserid(ctx) {

        hook_macros::real!(cuserid)(_string)
    }
}
    
hook_macros::hook! {
    unsafe fn dcgettext(
        _domainname: *mut libc::c_void,
        _msgid: *mut libc::c_void,
        _category: libc::c_int
    ) -> *mut libc::c_void => fizzle_dcgettext(ctx) {

        hook_macros::real!(dcgettext)(_domainname, _msgid, _category)
    }
}
    
hook_macros::hook! {
    unsafe fn dcngettext(
        _domain: *mut libc::c_void,
        _msgid1: *mut libc::c_void,
        _msgid2: *mut libc::c_void,
        _n: libc::c_long,
        _category: libc::c_int
    ) -> *mut libc::c_void => fizzle_dcngettext(ctx) {

        hook_macros::real!(dcngettext)(_domain, _msgid1, _msgid2, _n, _category)
    }
}
    
hook_macros::hook! {
    unsafe fn dgettext(
        _domainname: *mut libc::c_void,
        _msgid: *mut libc::c_void
    ) -> *mut libc::c_void => fizzle_dgettext(ctx) {

        hook_macros::real!(dgettext)(_domainname, _msgid)
    }
}
    
hook_macros::hook! {
    unsafe fn dlinfo(
        _handle: *mut libc::c_void,
        _request: libc::c_int,
        _arg: *mut libc::c_void
    ) -> libc::c_int => fizzle_dlinfo(ctx) {

        hook_macros::real!(dlinfo)(_handle, _request, _arg)
    }
}
    
hook_macros::hook! {
    unsafe fn dngettext(
        _domain: *mut libc::c_void,
        _msgid1: *mut libc::c_void,
        _msgid2: *mut libc::c_void,
        _n: libc::c_long
    ) -> *mut libc::c_void => fizzle_dngettext(ctx) {

        hook_macros::real!(dngettext)(_domain, _msgid1, _msgid2, _n)
    }
}
    
hook_macros::hook! {
    unsafe fn ecvt(
        _value: libc::c_double,
        _ndigit: libc::c_int,
        _decpt: *mut libc::c_void,
        _neg: *mut libc::c_void
    ) -> *mut libc::c_void => fizzle_ecvt(ctx) {

        hook_macros::real!(ecvt)(_value, _ndigit, _decpt, _neg)
    }
}
    
hook_macros::hook! {
    unsafe fn endfsent() => fizzle_endfsent(ctx) {

        hook_macros::real!(endfsent)()
    }
}
    
hook_macros::hook! {
    unsafe fn endgrent() => fizzle_endgrent(ctx) {

        hook_macros::real!(endgrent)()
    }
}
    
hook_macros::hook! {
    unsafe fn endhostent() => fizzle_endhostent(ctx) {

        hook_macros::real!(endhostent)()
    }
}
    
hook_macros::hook! {
    unsafe fn endmntent(
        _stream: *mut libc::c_void
    ) -> libc::c_int => fizzle_endmntent(ctx) {

        hook_macros::real!(endmntent)(_stream)
    }
}
    
hook_macros::hook! {
    unsafe fn endnetent() => fizzle_endnetent(ctx) {

        hook_macros::real!(endnetent)()
    }
}
    
hook_macros::hook! {
    unsafe fn endnetgrent() => fizzle_endnetgrent(ctx) {

        hook_macros::real!(endnetgrent)()
    }
}
    
hook_macros::hook! {
    unsafe fn endprotoent() => fizzle_endprotoent(ctx) {

        hook_macros::real!(endprotoent)()
    }
}
    
hook_macros::hook! {
    unsafe fn endpwent() => fizzle_endpwent(ctx) {

        hook_macros::real!(endpwent)()
    }
}
    
hook_macros::hook! {
    unsafe fn endservent() => fizzle_endservent(ctx) {

        hook_macros::real!(endservent)()
    }
}
    
hook_macros::hook! {
    unsafe fn endutent() => fizzle_endutent(ctx) {

        hook_macros::real!(endutent)()
    }
}
    
hook_macros::hook! {
    unsafe fn endutxent() => fizzle_endutxent(ctx) {

        hook_macros::real!(endutxent)()
    }
}
    
hook_macros::hook! {
    unsafe fn envz_add(
        _envz: *mut *mut libc::c_void,
        _envz_len: *mut libc::c_void,
        _name: *mut libc::c_void,
        _value: *mut libc::c_void
    ) -> libc::c_int => fizzle_envz_add(ctx) {

        hook_macros::real!(envz_add)(_envz, _envz_len, _name, _value)
    }
}
    
hook_macros::hook! {
    unsafe fn envz_merge(
        _envz: *mut *mut libc::c_void,
        _envz_len: *mut libc::c_void,
        _envz2: *mut libc::c_void,
        _envz2_len: libc::size_t,
        _override: libc::c_int
    ) -> libc::c_int => fizzle_envz_merge(ctx) {

        hook_macros::real!(envz_merge)(_envz, _envz_len, _envz2, _envz2_len, _override)
    }
}
    
hook_macros::hook! {
    unsafe fn envz_remove(
        _envz: *mut *mut libc::c_void,
        _envz_len: *mut libc::c_void,
        _name: *mut libc::c_void
    ) => fizzle_envz_remove(ctx) {

        hook_macros::real!(envz_remove)(_envz, _envz_len, _name)
    }
}
    
#[unsafe(no_mangle)]
pub unsafe extern "C" fn err(
        status: libc::c_int,
        _format: *const libc::c_char,
        _va_args: ...
    )  {
    let Some(_ctx) = crate::hooks::pre_hook() else {
        log::error!("err() called internally by Fizzle");
        std::process::exit(status);
    };


    log::error!("err() called by program");
    std::process::exit(status);
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn error(
        status: libc::c_int,
        _errnum: libc::c_int,
        _format: *mut libc::c_void,
        _va_args: ...
    ) {
    let Some(_ctx) = crate::hooks::pre_hook() else {
        log::error!("error({}) called internally by Fizzle", status);
        if status != 0 {
            std::process::exit(status);
        } else {
            return
        }
    };


    // TODO: implement proper error printing

    log::error!("error({}) called internally by program", status);
    if status != 0 {
        std::process::exit(status);
    } else {
        crate::hooks::post_hook();
    }
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn error_at_line(
        status: libc::c_int,
        _errnum: libc::c_int,
        _fname: *mut libc::c_void,
        _lineno: libc::c_uint,
        _format: *mut libc::c_void,
        _va_args: std::ffi::VaList
    ) {
    let Some(_ctx) = crate::hooks::pre_hook() else {
        log::error!("err({}) called internally by Fizzle", status);
        if status != 0 {
            std::process::exit(status);
        } else {
            return
        }
    };


    log::error!("error_at_line({}) called internally by program", status);
    if status != 0 {
        std::process::exit(status);
    } else {
        crate::hooks::post_hook();
    }
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn errx(
        status: libc::c_int,
        _format: *mut libc::c_void,
        _va_args: ...
    ) {
    let Some(_ctx) = crate::hooks::pre_hook() else {
        log::error!("errx() called internally by Fizzle");
        std::process::exit(status);
    };


    log::error!("errx() called by program");
    std::process::exit(status);
}

hook_macros::hook! {
    unsafe fn fbufsize(
        _stream: *mut libc::c_void
    ) -> libc::size_t => fizzle_fbufsize(ctx) {

        hook_macros::real!(fbufsize)(_stream)
    }
}
    
hook_macros::hook! {
    unsafe fn fcloseall() -> libc::c_int => fizzle_fcloseall(ctx) {

        hook_macros::real!(fcloseall)()
    }
}
    
hook_macros::hook! {
    unsafe fn fcvt(
        _value: libc::c_double,
        _ndigit: libc::c_int,
        _decpt: *mut libc::c_void,
        _neg: *mut libc::c_void
    ) -> *mut libc::c_void => fizzle_fcvt(ctx) {

        hook_macros::real!(fcvt)(_value, _ndigit, _decpt, _neg)
    }
}
    
hook_macros::hook! {
    unsafe fn fgetgrent(
        _stream: *mut libc::c_void
    ) -> *mut libc::c_void => fizzle_fgetgrent(ctx) {

        hook_macros::real!(fgetgrent)(_stream)
    }
}
    
hook_macros::hook! {
    unsafe fn fgetgrent_r(
        _stream: *mut libc::c_void,
        _result_buf: *mut libc::c_void,
        _buffer: *mut libc::c_void,
        _buflen: libc::size_t,
        _result: *mut *mut libc::c_void
    ) -> libc::c_int => fizzle_fgetgrent_r(ctx) {

        hook_macros::real!(fgetgrent_r)(_stream, _result_buf, _buffer, _buflen, _result)
    }
}
    
hook_macros::hook! {
    unsafe fn fgetpos64(
        _stream: *mut libc::c_void,
        _position: *mut libc::c_void
    ) -> libc::c_int => fizzle_fgetpos64(ctx) {

        hook_macros::real!(fgetpos64)(_stream, _position)
    }
}
    
hook_macros::hook! {
    unsafe fn fgetpwent(
        _stream: *mut libc::c_void
    ) -> *mut libc::c_void => fizzle_fgetpwent(ctx) {

        hook_macros::real!(fgetpwent)(_stream)
    }
}
    
hook_macros::hook! {
    unsafe fn fgetpwent_r(
        _stream: *mut libc::c_void,
        _result_buf: *mut libc::c_void,
        _buffer: *mut libc::c_void,
        _buflen: libc::size_t,
        _result: *mut *mut libc::c_void
    ) -> libc::c_int => fizzle_fgetpwent_r(ctx) {

        hook_macros::real!(fgetpwent_r)(_stream, _result_buf, _buffer, _buflen, _result)
    }
}
    
hook_macros::hook! {
    unsafe fn fgetws(
        _ws: *mut libc::c_void,
        _count: libc::c_int,
        _stream: *mut libc::c_void
    ) -> *mut libc::c_void => fizzle_fgetws(ctx) {

        hook_macros::real!(fgetws)(_ws, _count, _stream)
    }
}
    
hook_macros::hook! {
    unsafe fn fgetws_unlocked(
        _ws: *mut libc::c_void,
        _count: libc::c_int,
        _stream: *mut libc::c_void
    ) -> *mut libc::c_void => fizzle_fgetws_unlocked(ctx) {

        hook_macros::real!(fgetws_unlocked)(_ws, _count, _stream)
    }
}
    
hook_macros::hook! {
    unsafe fn flushlbf() => fizzle_flushlbf(ctx) {

        hook_macros::real!(flushlbf)()
    }
}
    
hook_macros::hook! {
    unsafe fn fmtmsg(
        _classification: libc::c_long,
        _label: *mut libc::c_void,
        _severity: libc::c_int,
        _text: *mut libc::c_void,
        _action: *mut libc::c_void,
        _tag: *mut libc::c_void
    ) -> libc::c_int => fizzle_fmtmsg(ctx) {

        hook_macros::real!(fmtmsg)(_classification, _label, _severity, _text, _action, _tag)
    }
}
    
hook_macros::hook! {
    unsafe fn fnmatch(
        _pattern: *mut libc::c_void,
        _string: *mut libc::c_void,
        _flags: libc::c_int
    ) -> libc::c_int => fizzle_fnmatch(ctx) {

        hook_macros::real!(fnmatch)(_pattern, _string, _flags)
    }
}
    
hook_macros::hook! {
    unsafe fn forkpty(
        _amaster: *mut libc::c_void,
        _name: *mut libc::c_void,
        _termp: *mut libc::c_void,
        _winp: *mut libc::c_void
    ) -> libc::c_int => fizzle_forkpty(ctx) {

        hook_macros::real!(forkpty)(_amaster, _name, _termp, _winp)
    }
}
    
hook_macros::hook! {
    unsafe fn fpathconf(
        _filedes: libc::c_int,
        _parameter: libc::c_int
    ) -> libc::c_long => fizzle_fpathconf(ctx) {

        hook_macros::real!(fpathconf)(_filedes, _parameter)
    }
}
    
hook_macros::hook! {
    unsafe fn fpending(
        _stream: *mut libc::c_void
    ) -> libc::size_t => fizzle_fpending(ctx) {

        hook_macros::real!(fpending)(_stream)
    }
}
    
hook_macros::hook! {
    unsafe fn fputws(
        _ws: *mut libc::c_void,
        _stream: *mut libc::c_void
    ) -> libc::c_int => fizzle_fputws(ctx) {

        hook_macros::real!(fputws)(_ws, _stream)
    }
}
    
hook_macros::hook! {
    unsafe fn fputws_unlocked(
        _ws: *mut libc::c_void,
        _stream: *mut libc::c_void
    ) -> libc::c_int => fizzle_fputws_unlocked(ctx) {

        hook_macros::real!(fputws_unlocked)(_ws, _stream)
    }
}
    
hook_macros::hook! {
    unsafe fn free(
        _ptr: *mut libc::c_void
    ) => fizzle_free(ctx) {

        hook_macros::real!(free)(_ptr)
    }
}
    
hook_macros::hook! {
    unsafe fn fsetlocking(
        _stream: *mut libc::c_void,
        _type: libc::c_int
    ) -> libc::c_int => fizzle_fsetlocking(ctx) {

        hook_macros::real!(fsetlocking)(_stream, _type)
    }
}
    
hook_macros::hook! {
    unsafe fn fsetpos64(
        _stream: *mut libc::c_void,
        _position: *mut libc::c_void
    ) -> libc::c_int => fizzle_fsetpos64(ctx) {

        hook_macros::real!(fsetpos64)(_stream, _position)
    }
}
    
hook_macros::hook! {
    unsafe fn fwide(
        _stream: *mut libc::c_void,
        _mode: libc::c_int
    ) -> libc::c_int => fizzle_fwide(ctx) {

        hook_macros::real!(fwide)(_stream, _mode)
    }
}
    
#[unsafe(no_mangle)]
pub unsafe extern "C" fn fwscanf(
        _stream: *mut libc::c_void,
        _template: *mut libc::c_void,
        _va_args: ...
    ) -> libc::c_int  {
    let Some(mut ctx) = crate::hooks::pre_hook() else {
        panic!("fwscanf() unimplemented for Fizzle internal use");
    };


    todo!("fwscanf");
    crate::hooks::post_hook();
}

hook_macros::hook! {
    unsafe fn gammal(
        _x: libc::c_long
    ) -> libc::c_double => fizzle_gammal(ctx) {

        hook_macros::real!(gammal)(_x)
    }
}
    
hook_macros::hook! {
    unsafe fn get_avphys_pages() -> libc::c_long => fizzle_get_avphys_pages(ctx) {

        hook_macros::real!(get_avphys_pages)()
    }
}
    
hook_macros::hook! {
    unsafe fn get_current_dir_name() -> *mut libc::c_void => fizzle_get_current_dir_name(ctx) {

        hook_macros::real!(get_current_dir_name)()
    }
}
    
hook_macros::hook! {
    unsafe fn get_nprocs_conf() -> libc::c_int => fizzle_get_nprocs_conf(ctx) {

        hook_macros::real!(get_nprocs_conf)()
    }
}
    
hook_macros::hook! {
    unsafe fn get_phys_pages() -> libc::c_long => fizzle_get_phys_pages(ctx) {

        hook_macros::real!(get_phys_pages)()
    }
}
    
hook_macros::hook! {
    unsafe fn getc_unlocked(
        _stream: *mut libc::c_void
    ) -> libc::c_int => fizzle_getc_unlocked(ctx) {

        hook_macros::real!(getc_unlocked)(_stream)
    }
}
    
hook_macros::hook! {
    unsafe fn getchar() -> libc::c_int => fizzle_getchar(ctx) {

        hook_macros::real!(getchar)()
    }
}
    
hook_macros::hook! {
    unsafe fn getchar_unlocked() -> libc::c_int => fizzle_getchar_unlocked(ctx) {

        hook_macros::real!(getchar_unlocked)()
    }
}
    
hook_macros::hook! {
    unsafe fn getcwd(
        _buffer: *mut libc::c_void,
        _size: libc::size_t
    ) -> *mut libc::c_void => fizzle_getcwd(ctx) {

        hook_macros::real!(getcwd)(_buffer, _size)
    }
}
    
hook_macros::hook! {
    unsafe fn getdate(
        _string: *mut libc::c_void
    ) -> *mut libc::c_void => fizzle_getdate(ctx) {

        hook_macros::real!(getdate)(_string)
    }
}
    
hook_macros::hook! {
    unsafe fn getdate_r(
        _string: *mut libc::c_void,
        _tp: *mut libc::c_void
    ) -> libc::c_int => fizzle_getdate_r(ctx) {

        hook_macros::real!(getdate_r)(_string, _tp)
    }
}
    
hook_macros::hook! {
    unsafe fn getfsent() -> *mut libc::c_void => fizzle_getfsent(ctx) {

        hook_macros::real!(getfsent)()
    }
}
    
hook_macros::hook! {
    unsafe fn getfsfile(
        _name: *mut libc::c_void
    ) -> *mut libc::c_void => fizzle_getfsfile(ctx) {

        hook_macros::real!(getfsfile)(_name)
    }
}
    
hook_macros::hook! {
    unsafe fn getfsspec(
        _name: *mut libc::c_void
    ) -> *mut libc::c_void => fizzle_getfsspec(ctx) {

        hook_macros::real!(getfsspec)(_name)
    }
}
    
hook_macros::hook! {
    unsafe fn getgrent() -> *mut libc::c_void => fizzle_getgrent(ctx) {

        hook_macros::real!(getgrent)()
    }
}
    
hook_macros::hook! {
    unsafe fn getgrent_r(
        _result_buf: *mut libc::c_void,
        _buffer: *mut libc::c_void,
        _buflen: libc::size_t,
        _result: *mut *mut libc::c_void
    ) -> libc::c_int => fizzle_getgrent_r(ctx) {

        hook_macros::real!(getgrent_r)(_result_buf, _buffer, _buflen, _result)
    }
}
    
hook_macros::hook! {
    unsafe fn getgrgid(
        _gid: libc::gid_t
    ) -> *mut libc::c_void => fizzle_getgrgid(ctx) {

        hook_macros::real!(getgrgid)(_gid)
    }
}
    
hook_macros::hook! {
    unsafe fn getgrgid_r(
        _gid: libc::gid_t,
        _result_buf: *mut libc::c_void,
        _buffer: *mut libc::c_void,
        _buflen: libc::size_t,
        _result: *mut *mut libc::c_void
    ) -> libc::c_int => fizzle_getgrgid_r(ctx) {

        hook_macros::real!(getgrgid_r)(_gid, _result_buf, _buffer, _buflen, _result)
    }
}
    
hook_macros::hook! {
    unsafe fn getgrnam(
        _name: *mut libc::c_void
    ) -> *mut libc::c_void => fizzle_getgrnam(ctx) {

        hook_macros::real!(getgrnam)(_name)
    }
}
    
hook_macros::hook! {
    unsafe fn getgrnam_r(
        _name: *mut libc::c_void,
        _result_buf: *mut libc::c_void,
        _buffer: *mut libc::c_void,
        _buflen: libc::size_t,
        _result: *mut *mut libc::c_void
    ) -> libc::c_int => fizzle_getgrnam_r(ctx) {

        hook_macros::real!(getgrnam_r)(_name, _result_buf, _buffer, _buflen, _result)
    }
}
    
hook_macros::hook! {
    unsafe fn getgrouplist(
        _user: *mut libc::c_void,
        _group: libc::gid_t,
        _groups: *mut libc::c_void,
        _ngroups: *mut libc::c_void
    ) -> libc::c_int => fizzle_getgrouplist(ctx) {

        hook_macros::real!(getgrouplist)(_user, _group, _groups, _ngroups)
    }
}
    
hook_macros::hook! {
    unsafe fn gethostbyaddr_r(
        _addr: *mut libc::c_void,
        _length: libc::socklen_t,
        _format: libc::c_int,
        _result_buf: *mut libc::c_void,
        _buf: *mut libc::c_void,
        _buflen: libc::size_t,
        _result: *mut *mut libc::c_void,
        _h_errnop: *mut libc::c_void
    ) -> libc::c_int => fizzle_gethostbyaddr_r(ctx) {

        hook_macros::real!(gethostbyaddr_r)(_addr, _length, _format, _result_buf, _buf, _buflen, _result, _h_errnop)
    }
}
    
hook_macros::hook! {
    unsafe fn gethostbyname2_r(
        _name: *mut libc::c_void,
        _af: libc::c_int,
        _result_buf: *mut libc::c_void,
        _buf: *mut libc::c_void,
        _buflen: libc::size_t,
        _result: *mut *mut libc::c_void,
        _h_errnop: *mut libc::c_void
    ) -> libc::c_int => fizzle_gethostbyname2_r(ctx) {

        hook_macros::real!(gethostbyname2_r)(_name, _af, _result_buf, _buf, _buflen, _result, _h_errnop)
    }
}
    
hook_macros::hook! {
    unsafe fn gethostbyname_r(
        _name: *mut libc::c_void,
        _result_buf: *mut libc::c_void,
        _buf: *mut libc::c_void,
        _buflen: libc::size_t,
        _result: *mut *mut libc::c_void,
        _h_errnop: *mut libc::c_void
    ) -> libc::c_int => fizzle_gethostbyname_r(ctx) {

        hook_macros::real!(gethostbyname_r)(_name, _result_buf, _buf, _buflen, _result, _h_errnop)
    }
}
    
hook_macros::hook! {
    unsafe fn gethostent() -> *mut libc::c_void => fizzle_gethostent(ctx) {

        hook_macros::real!(gethostent)()
    }
}
    
hook_macros::hook! {
    unsafe fn gethostid() -> libc::c_long => fizzle_gethostid(ctx) {

        hook_macros::real!(gethostid)()
    }
}
    
hook_macros::hook! {
    unsafe fn getlogin() -> *mut libc::c_void => fizzle_getlogin(ctx) {

        hook_macros::real!(getlogin)()
    }
}
    
hook_macros::hook! {
    unsafe fn getmntent(
        _stream: *mut libc::c_void
    ) -> *mut libc::c_void => fizzle_getmntent(ctx) {

        hook_macros::real!(getmntent)(_stream)
    }
}
    
hook_macros::hook! {
    unsafe fn getmntent_r(
        _stream: *mut libc::c_void,
        _result: *mut libc::c_void,
        _buffer: *mut libc::c_void,
        _bufsize: libc::c_int
    ) -> *mut libc::c_void => fizzle_getmntent_r(ctx) {

        hook_macros::real!(getmntent_r)(_stream, _result, _buffer, _bufsize)
    }
}
    
hook_macros::hook! {
    unsafe fn getnetbyaddr(
        _net: libc::__u32,
        _type: libc::c_int
    ) -> *mut libc::c_void => fizzle_getnetbyaddr(ctx) {

        hook_macros::real!(getnetbyaddr)(_net, _type)
    }
}
    
hook_macros::hook! {
    unsafe fn getnetbyname(
        _name: *mut libc::c_void
    ) -> *mut libc::c_void => fizzle_getnetbyname(ctx) {

        hook_macros::real!(getnetbyname)(_name)
    }
}
    
hook_macros::hook! {
    unsafe fn getnetent() -> *mut libc::c_void => fizzle_getnetent(ctx) {

        hook_macros::real!(getnetent)()
    }
}
    
hook_macros::hook! {
    unsafe fn getnetgrent(
        _hostp: *mut *mut libc::c_void,
        _userp: *mut *mut libc::c_void,
        _domainp: *mut *mut libc::c_void
    ) -> libc::c_int => fizzle_getnetgrent(ctx) {

        hook_macros::real!(getnetgrent)(_hostp, _userp, _domainp)
    }
}
    
hook_macros::hook! {
    unsafe fn getnetgrent_r(
        _hostp: *mut *mut libc::c_void,
        _userp: *mut *mut libc::c_void,
        _domainp: *mut *mut libc::c_void,
        _buffer: *mut libc::c_void,
        _buflen: libc::size_t
    ) -> libc::c_int => fizzle_getnetgrent_r(ctx) {

        hook_macros::real!(getnetgrent_r)(_hostp, _userp, _domainp, _buffer, _buflen)
    }
}
    
hook_macros::hook! {
    unsafe fn getopt(
        _argc: libc::c_int,
        _argv: *mut *mut libc::c_void,
        _options: *mut libc::c_void
    ) -> libc::c_int => fizzle_getopt(ctx) {

        hook_macros::real!(getopt)(_argc, _argv, _options)
    }
}
    
hook_macros::hook! {
    unsafe fn getopt_long(
        _argc: libc::c_int,
        _argv: *mut *mut libc::c_void,
        _shortopts: *mut libc::c_void,
        _longopts: *mut libc::c_void,
        _indexptr: *mut libc::c_void
    ) -> libc::c_int => fizzle_getopt_long(ctx) {

        hook_macros::real!(getopt_long)(_argc, _argv, _shortopts, _longopts, _indexptr)
    }
}
    
hook_macros::hook! {
    unsafe fn getopt_long_only(
        _argc: libc::c_int,
        _argv: *mut *mut libc::c_void,
        _shortopts: *mut libc::c_void,
        _longopts: *mut libc::c_void,
        _indexptr: *mut libc::c_void
    ) -> libc::c_int => fizzle_getopt_long_only(ctx) {

        hook_macros::real!(getopt_long_only)(_argc, _argv, _shortopts, _longopts, _indexptr)
    }
}
    
hook_macros::hook! {
    unsafe fn getpass(
        _prompt: *mut libc::c_void
    ) -> *mut libc::c_void => fizzle_getpass(ctx) {

        hook_macros::real!(getpass)(_prompt)
    }
}
    
hook_macros::hook! {
    unsafe fn getprotobyname(
        _name: *mut libc::c_void
    ) -> *mut libc::c_void => fizzle_getprotobyname(ctx) {

        hook_macros::real!(getprotobyname)(_name)
    }
}
    
hook_macros::hook! {
    unsafe fn getprotobynumber(
        _protocol: libc::c_int
    ) -> *mut libc::c_void => fizzle_getprotobynumber(ctx) {

        hook_macros::real!(getprotobynumber)(_protocol)
    }
}
    
hook_macros::hook! {
    unsafe fn getprotoent() -> *mut libc::c_void => fizzle_getprotoent(ctx) {

        hook_macros::real!(getprotoent)()
    }
}
    
hook_macros::hook! {
    unsafe fn getpwent() -> *mut libc::c_void => fizzle_getpwent(ctx) {

        hook_macros::real!(getpwent)()
    }
}
    
hook_macros::hook! {
    unsafe fn getpwent_r(
        _result_buf: *mut libc::c_void,
        _buffer: *mut libc::c_void,
        _buflen: libc::size_t,
        _result: *mut *mut libc::c_void
    ) -> libc::c_int => fizzle_getpwent_r(ctx) {

        hook_macros::real!(getpwent_r)(_result_buf, _buffer, _buflen, _result)
    }
}
    
hook_macros::hook! {
    unsafe fn getpwnam_r(
        name: *mut libc::c_void,
        result_buf: *mut libc::c_void,
        buffer: *mut libc::c_void,
        buflen: libc::size_t,
        result: *mut *mut libc::c_void
    ) -> libc::c_int => fizzle_getpwnam_r(ctx) {

        hook_macros::real!(getpwnam_r)(name, result_buf, buffer, buflen, result)
    }
}
    
hook_macros::hook! {
    unsafe fn getpwuid_r(
        _uid: libc::uid_t,
        _result_buf: *mut libc::c_void,
        _buffer: *mut libc::c_void,
        _buflen: libc::size_t,
        _result: *mut *mut libc::c_void
    ) -> libc::c_int => fizzle_getpwuid_r(ctx) {

        hook_macros::real!(getpwuid_r)(_uid, _result_buf, _buffer, _buflen, _result)
    }
}
    
hook_macros::hook! {
    unsafe fn gets(
        _s: *mut libc::c_void
    ) -> *mut libc::c_void => fizzle_gets(ctx) {

        hook_macros::real!(gets)(_s)
    }
}
    
hook_macros::hook! {
    unsafe fn getservbyport(
        _port: libc::c_int,
        _proto: *mut libc::c_void
    ) -> *mut libc::c_void => fizzle_getservbyport(ctx) {

        hook_macros::real!(getservbyport)(_port, _proto)
    }
}
    
hook_macros::hook! {
    unsafe fn getservent() -> *mut libc::c_void => fizzle_getservent(ctx) {

        hook_macros::real!(getservent)()
    }
}
    
hook_macros::hook! {
    unsafe fn gettext(
        _msgid: *mut libc::c_void
    ) -> *mut libc::c_void => fizzle_gettext(ctx) {

        hook_macros::real!(gettext)(_msgid)
    }
}
    
hook_macros::hook! {
    unsafe fn getutent() -> *mut libc::c_void => fizzle_getutent(ctx) {

        hook_macros::real!(getutent)()
    }
}
    
hook_macros::hook! {
    unsafe fn getutent_r(
        _buffer: *mut libc::c_void,
        _result: *mut *mut libc::c_void
    ) -> libc::c_int => fizzle_getutent_r(ctx) {

        hook_macros::real!(getutent_r)(_buffer, _result)
    }
}
    
hook_macros::hook! {
    unsafe fn getutid(
        _id: *mut libc::c_void
    ) -> *mut libc::c_void => fizzle_getutid(ctx) {

        hook_macros::real!(getutid)(_id)
    }
}
    
hook_macros::hook! {
    unsafe fn getutid_r(
        _id: *mut libc::c_void,
        _buffer: *mut libc::c_void,
        _result: *mut *mut libc::c_void
    ) -> libc::c_int => fizzle_getutid_r(ctx) {

        hook_macros::real!(getutid_r)(_id, _buffer, _result)
    }
}
    
hook_macros::hook! {
    unsafe fn getutline(
        _line: *mut libc::c_void
    ) -> *mut libc::c_void => fizzle_getutline(ctx) {

        hook_macros::real!(getutline)(_line)
    }
}
    
hook_macros::hook! {
    unsafe fn getutline_r(
        _line: *mut libc::c_void,
        _buffer: *mut libc::c_void,
        _result: *mut *mut libc::c_void
    ) -> libc::c_int => fizzle_getutline_r(ctx) {

        hook_macros::real!(getutline_r)(_line, _buffer, _result)
    }
}
    
hook_macros::hook! {
    unsafe fn getutxent() -> *mut libc::c_void => fizzle_getutxent(ctx) {

        hook_macros::real!(getutxent)()
    }
}
    
hook_macros::hook! {
    unsafe fn getutxid(
        _id: *mut libc::c_void
    ) -> *mut libc::c_void => fizzle_getutxid(ctx) {

        hook_macros::real!(getutxid)(_id)
    }
}
    
hook_macros::hook! {
    unsafe fn getutxline(
        _line: *mut libc::c_void
    ) -> *mut libc::c_void => fizzle_getutxline(ctx) {

        hook_macros::real!(getutxline)(_line)
    }
}
    
hook_macros::hook! {
    unsafe fn getw(
        _stream: *mut libc::c_void
    ) -> libc::c_int => fizzle_getw(ctx) {

        hook_macros::real!(getw)(_stream)
    }
}
    
hook_macros::hook! {
    unsafe fn getwd(
        _buffer: *mut libc::c_void
    ) -> *mut libc::c_void => fizzle_getwd(ctx) {

        hook_macros::real!(getwd)(_buffer)
    }
}
    
hook_macros::hook! {
    unsafe fn globfree(
        _pglob: *mut libc::c_void
    ) => fizzle_globfree(ctx) {

        hook_macros::real!(globfree)(_pglob)
    }
}
    
hook_macros::hook! {
    unsafe fn globfree64(
        _pglob: *mut libc::c_void
    ) => fizzle_globfree64(ctx) {

        hook_macros::real!(globfree64)(_pglob)
    }
}
    
hook_macros::hook! {
    unsafe fn gmtime(
        _time: *mut libc::c_void
    ) -> *mut libc::c_void => fizzle_gmtime(ctx) {

        hook_macros::real!(gmtime)(_time)
    }
}
    
hook_macros::hook! {
    unsafe fn gmtime_r(
        _time: *mut libc::c_void,
        _resultp: *mut libc::c_void
    ) -> *mut libc::c_void => fizzle_gmtime_r(ctx) {

        hook_macros::real!(gmtime_r)(_time, _resultp)
    }
}
    
hook_macros::hook! {
    unsafe fn grantpt(
        _filedes: libc::c_int
    ) -> libc::c_int => fizzle_grantpt(ctx) {

        hook_macros::real!(grantpt)(_filedes)
    }
}
    
hook_macros::hook! {
    unsafe fn hcreate(
        _nel: libc::size_t
    ) -> libc::c_int => fizzle_hcreate(ctx) {

        hook_macros::real!(hcreate)(_nel)
    }
}
    
hook_macros::hook! {
    unsafe fn hcreate_r(
        _nel: libc::size_t,
        _htab: *mut libc::c_void
    ) -> libc::c_int => fizzle_hcreate_r(ctx) {

        hook_macros::real!(hcreate_r)(_nel, _htab)
    }
}
    
hook_macros::hook! {
    unsafe fn hdestroy() => fizzle_hdestroy(ctx) {

        hook_macros::real!(hdestroy)()
    }
}
    
hook_macros::hook! {
    unsafe fn hdestroy_r(
        _htab: *mut libc::c_void
    ) => fizzle_hdestroy_r(ctx) {

        hook_macros::real!(hdestroy_r)(_htab)
    }
}
    
hook_macros::hook! {
    unsafe fn iconv_close(
        _cd: libc::iconv_t
    ) -> libc::c_int => fizzle_iconv_close(ctx) {

        hook_macros::real!(iconv_close)(_cd)
    }
}
    
hook_macros::hook! {
    unsafe fn iconv_open(
        _tocode: *mut libc::c_void,
        _fromcode: *mut libc::c_void
    ) -> libc::iconv_t => fizzle_iconv_open(ctx) {

        hook_macros::real!(iconv_open)(_tocode, _fromcode)
    }
}
    
hook_macros::hook! {
    unsafe fn if_freenameindex(
        _ptr: *mut libc::c_void
    ) => fizzle_if_freenameindex(ctx) {

        hook_macros::real!(if_freenameindex)(_ptr)
    }
}
    
hook_macros::hook! {
    unsafe fn if_indextoname(
        _ifindex: libc::c_uint,
        _ifname: *mut libc::c_void
    ) -> *mut libc::c_void => fizzle_if_indextoname(ctx) {

        hook_macros::real!(if_indextoname)(_ifindex, _ifname)
    }
}
    
hook_macros::hook! {
    unsafe fn if_nameindex() -> *mut libc::c_void => fizzle_if_nameindex(ctx) {

        hook_macros::real!(if_nameindex)()
    }
}
    
hook_macros::hook! {
    unsafe fn if_nametoindex(
        _ifname: *mut libc::c_void
    ) -> libc::c_uint => fizzle_if_nametoindex(ctx) {

        hook_macros::real!(if_nametoindex)(_ifname)
    }
}
    
hook_macros::hook! {
    unsafe fn initgroups(
        _user: *mut libc::c_void,
        _group: libc::gid_t
    ) -> libc::c_int => fizzle_initgroups(ctx) {

        hook_macros::real!(initgroups)(_user, _group)
    }
}
    
hook_macros::hook! {
    unsafe fn initstate(
        _seed: libc::c_uint,
        _state: *mut libc::c_void,
        _size: libc::size_t
    ) -> *mut libc::c_void => fizzle_initstate(ctx) {

        hook_macros::real!(initstate)(_seed, _state, _size)
    }
}
    
hook_macros::hook! {
    unsafe fn innetgr(
        _netgroup: *mut libc::c_void,
        _host: *mut libc::c_void,
        _user: *mut libc::c_void,
        _domain: *mut libc::c_void
    ) -> libc::c_int => fizzle_innetgr(ctx) {

        hook_macros::real!(innetgr)(_netgroup, _host, _user, _domain)
    }
}
    
hook_macros::hook! {
    unsafe fn l64a(
        _n: libc::c_long
    ) -> *mut libc::c_void => fizzle_l64a(ctx) {

        hook_macros::real!(l64a)(_n)
    }
}
    
hook_macros::hook! {
    unsafe fn lio_listio64(
        _mode: libc::c_int,
        _list: *mut libc::c_void,
        _nent: libc::c_int,
        _sig: *mut libc::c_void
    ) -> libc::c_int => fizzle_lio_listio64(ctx) {

        hook_macros::real!(lio_listio64)(_mode, _list, _nent, _sig)
    }
}
    
hook_macros::hook! {
    unsafe fn localeconv() -> *mut libc::c_void => fizzle_localeconv(ctx) {

        hook_macros::real!(localeconv)()
    }
}
    
hook_macros::hook! {
    unsafe fn localtime(
        _time: *mut libc::c_void
    ) -> *mut libc::c_void => fizzle_localtime(ctx) {

        hook_macros::real!(localtime)(_time)
    }
}
    
hook_macros::hook! {
    unsafe fn localtime_r(
        _time: *mut libc::c_void,
        _resultp: *mut libc::c_void
    ) -> *mut libc::c_void => fizzle_localtime_r(ctx) {

        hook_macros::real!(localtime_r)(_time, _resultp)
    }
}
    
hook_macros::hook! {
    unsafe fn login(
        _entry: *mut libc::c_void
    ) => fizzle_login(ctx) {

        hook_macros::real!(login)(_entry)
    }
}
    
hook_macros::hook! {
    unsafe fn login_tty(
        _filedes: libc::c_int
    ) -> libc::c_int => fizzle_login_tty(ctx) {

        hook_macros::real!(login_tty)(_filedes)
    }
}
    
hook_macros::hook! {
    unsafe fn logout(
        _ut_line: *mut libc::c_void
    ) -> libc::c_int => fizzle_logout(ctx) {

        hook_macros::real!(logout)(_ut_line)
    }
}
    
hook_macros::hook! {
    unsafe fn logwtmp(
        _ut_line: *mut libc::c_void,
        _ut_name: *mut libc::c_void,
        _ut_host: *mut libc::c_void
    ) => fizzle_logwtmp(ctx) {

        hook_macros::real!(logwtmp)(_ut_line, _ut_name, _ut_host)
    }
}
    
hook_macros::hook! {
    unsafe fn longjmp(
        _state: *mut libc::c_void,
        _value: libc::c_int
    ) => fizzle_longjmp(ctx) {

        hook_macros::real!(longjmp)(_state, _value)
    }
}
    
hook_macros::hook! {
    unsafe fn mallinfo2() -> libc::mallinfo2 => fizzle_mallinfo2(ctx) {

        hook_macros::real!(mallinfo2)()
    }
}
    
hook_macros::hook! {
    unsafe fn malloc(
        _size: libc::size_t
    ) -> *mut libc::c_void => fizzle_malloc(ctx) {

        hook_macros::real!(malloc)(_size)
    }
}
    
hook_macros::hook! {
    unsafe fn mallopt(
        _param: libc::c_int,
        _value: libc::c_int
    ) -> libc::c_int => fizzle_mallopt(ctx) {

        hook_macros::real!(mallopt)(_param, _value)
    }
}
    
hook_macros::hook! {
    unsafe fn mblen(
        _string: *mut libc::c_void,
        _size: libc::size_t
    ) -> libc::c_int => fizzle_mblen(ctx) {

        hook_macros::real!(mblen)(_string, _size)
    }
}
    
hook_macros::hook! {
    unsafe fn mbrlen(
        _s: *mut libc::c_void,
        _n: libc::size_t,
        _ps: *mut libc::c_void
    ) -> libc::size_t => fizzle_mbrlen(ctx) {

        hook_macros::real!(mbrlen)(_s, _n, _ps)
    }
}
    
hook_macros::hook! {
    unsafe fn mbrtowc(
        _pwc: *mut libc::c_void,
        _s: *mut libc::c_void,
        _n: libc::size_t,
        _ps: *mut libc::c_void
    ) -> libc::size_t => fizzle_mbrtowc(ctx) {

        hook_macros::real!(mbrtowc)(_pwc, _s, _n, _ps)
    }
}
    
hook_macros::hook! {
    unsafe fn mbsnrtowcs(
        _dst: *mut libc::c_void,
        _src: *mut *mut libc::c_void,
        _nmc: libc::size_t,
        _len: libc::size_t,
        _ps: *mut libc::c_void
    ) -> libc::size_t => fizzle_mbsnrtowcs(ctx) {

        hook_macros::real!(mbsnrtowcs)(_dst, _src, _nmc, _len, _ps)
    }
}
    
hook_macros::hook! {
    unsafe fn mbsrtowcs(
        _dst: *mut libc::c_void,
        _src: *mut *mut libc::c_void,
        _len: libc::size_t,
        _ps: *mut libc::c_void
    ) -> libc::size_t => fizzle_mbsrtowcs(ctx) {

        hook_macros::real!(mbsrtowcs)(_dst, _src, _len, _ps)
    }
}
    
hook_macros::hook! {
    unsafe fn mbstowcs(
        _wstring: *mut libc::c_void,
        _string: *mut libc::c_void,
        _size: libc::size_t
    ) -> libc::size_t => fizzle_mbstowcs(ctx) {

        hook_macros::real!(mbstowcs)(_wstring, _string, _size)
    }
}
    
hook_macros::hook! {
    unsafe fn mbtowc(
        _result: *mut libc::c_void,
        _string: *mut libc::c_void,
        _size: libc::size_t
    ) -> libc::c_int => fizzle_mbtowc(ctx) {

        hook_macros::real!(mbtowc)(_result, _string, _size)
    }
}
    
hook_macros::hook! {
    unsafe fn mcheck(
        abortfn: unsafe extern "C" fn(libc::__exit_status) -> *mut libc::c_void
    ) -> libc::c_int => fizzle_mcheck(ctx) {

        hook_macros::real!(mcheck)(abortfn)
    }
}
    
hook_macros::hook! {
    unsafe fn memalign(
        _boundary: libc::size_t,
        _size: libc::size_t
    ) -> *mut libc::c_void => fizzle_memalign(ctx) {

        hook_macros::real!(memalign)(_boundary, _size)
    }
}
    
hook_macros::hook! {
    unsafe fn mktime(
        _brokentime: *mut libc::c_void
    ) -> libc::time_t => fizzle_mktime(ctx) {

        hook_macros::real!(mktime)(_brokentime)
    }
}
    
hook_macros::hook! {
    unsafe fn mtrace() => fizzle_mtrace(ctx) {

        hook_macros::real!(mtrace)()
    }
}
    
hook_macros::hook! {
    unsafe fn mtx_lock(
        _mutex: *mut libc::c_void
    ) -> libc::c_int => fizzle_mtx_lock(ctx) {

        hook_macros::real!(mtx_lock)(_mutex)
    }
}
    
hook_macros::hook! {
    unsafe fn mtx_timedlock(
        _mutex: *mut libc::c_void,
        _time_point: *mut libc::c_void
    ) -> libc::c_int => fizzle_mtx_timedlock(ctx) {

        hook_macros::real!(mtx_timedlock)(_mutex, _time_point)
    }
}
    
hook_macros::hook! {
    unsafe fn mtx_trylock(
        _mutex: *mut libc::c_void
    ) -> libc::c_int => fizzle_mtx_trylock(ctx) {

        hook_macros::real!(mtx_trylock)(_mutex)
    }
}
    
hook_macros::hook! {
    unsafe fn muntrace() => fizzle_muntrace(ctx) {

        hook_macros::real!(muntrace)()
    }
}
    
hook_macros::hook! {
    unsafe fn ngettext(
        _msgid1: *mut libc::c_void,
        _msgid2: *mut libc::c_void,
        _n: libc::c_long
    ) -> *mut libc::c_void => fizzle_ngettext(ctx) {

        hook_macros::real!(ngettext)(_msgid1, _msgid2, _n)
    }
}
    
hook_macros::hook! {
    unsafe fn nice(
        _increment: libc::c_int
    ) -> libc::c_int => fizzle_nice(ctx) {

        hook_macros::real!(nice)(_increment)
    }
}
    
hook_macros::hook! {
    unsafe fn obstack_base(
        _obstack_ptr: *mut libc::c_void
    ) -> *mut libc::c_void => fizzle_obstack_base(ctx) {

        hook_macros::real!(obstack_base)(_obstack_ptr)
    }
}
    
hook_macros::hook! {
    unsafe fn obstack_next_free(
        _obstack_ptr: *mut libc::c_void
    ) -> *mut libc::c_void => fizzle_obstack_next_free(ctx) {

        hook_macros::real!(obstack_next_free)(_obstack_ptr)
    }
}
    
#[unsafe(no_mangle)]
pub unsafe extern "C" fn obstack_printf(
        _obstack: *mut libc::c_void,
        _template: *mut libc::c_void,
        _va_args: ...
    ) -> libc::c_int  {
    let Some(mut ctx) = crate::hooks::pre_hook() else {
        panic!("obstack_printf() unimplemented for Fizzle internal use");
    };


    todo!("obstack_printf");
    crate::hooks::post_hook();
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn obstack_vprintf(
        _obstack: *mut libc::c_void,
        _template: *mut libc::c_void,
        _ap: std::ffi::VaList
    ) -> libc::c_int  {
    let Some(mut ctx) = crate::hooks::pre_hook() else {
        panic!("obstack_vprintf() unimplemented for Fizzle internal use");
    };


    todo!("obstack_vprintf");
    crate::hooks::post_hook();
}

hook_macros::hook! {
    unsafe fn openpty(
        _amaster: *mut libc::c_void,
        _aslave: *mut libc::c_void,
        _name: *mut libc::c_void,
        _termp: *mut libc::c_void,
        _winp: *mut libc::c_void
    ) -> libc::c_int => fizzle_openpty(ctx) {

        hook_macros::real!(openpty)(_amaster, _aslave, _name, _termp, _winp)
    }
}
    
hook_macros::hook! {
    unsafe fn pathconf(
        _filename: *mut libc::c_void,
        _parameter: libc::c_int
    ) -> libc::c_long => fizzle_pathconf(ctx) {

        hook_macros::real!(pathconf)(_filename, _parameter)
    }
}
    
hook_macros::hook! {
    unsafe fn perror(
        _message: *mut libc::c_void
    ) => fizzle_perror(ctx) {

        hook_macros::real!(perror)(_message)
    }
}
    
hook_macros::hook! {
    unsafe fn posix_memalign(
        _memptr: *mut *mut libc::c_void,
        _alignment: libc::size_t,
        _size: libc::size_t
    ) -> libc::c_int => fizzle_posix_memalign(ctx) {

        hook_macros::real!(posix_memalign)(_memptr, _alignment, _size)
    }
}
    
hook_macros::hook! {
    unsafe fn ppc_get_timebase_freq() -> libc::__u64 => fizzle_ppc_get_timebase_freq(ctx) {

        hook_macros::real!(ppc_get_timebase_freq)()
    }
}
    
hook_macros::hook! {
    unsafe fn printf_size(
        _fp: *mut libc::c_void,
        _info: *mut libc::c_void,
        _args: *mut *mut libc::c_void
    ) -> libc::c_int => fizzle_printf_size(ctx) {

        hook_macros::real!(printf_size)(_fp, _info, _args)
    }
}
    
hook_macros::hook! {
    unsafe fn psignal(
        _signum: libc::c_int,
        _message: *mut libc::c_void
    ) => fizzle_psignal(ctx) {

        hook_macros::real!(psignal)(_signum, _message)
    }
}
    
hook_macros::hook! {
    unsafe fn pthread_attr_getsigmask_np(
        _attr: *mut libc::c_void,
        _sigmask: *mut libc::c_void
    ) -> libc::c_int => fizzle_pthread_attr_getsigmask_np(ctx) {

        hook_macros::real!(pthread_attr_getsigmask_np)(_attr, _sigmask)
    }
}
    
hook_macros::hook! {
    unsafe fn pthread_attr_setsigmask_np(
        _attr: *mut libc::c_void,
        _sigmask: *mut libc::c_void
    ) -> libc::c_int => fizzle_pthread_attr_setsigmask_np(ctx) {

        hook_macros::real!(pthread_attr_setsigmask_np)(_attr, _sigmask)
    }
}
    
hook_macros::hook! {
    unsafe fn pthread_getattr_default_np(
        _attr: *mut libc::c_void
    ) -> libc::c_int => fizzle_pthread_getattr_default_np(ctx) {

        hook_macros::real!(pthread_getattr_default_np)(_attr)
    }
}
    
hook_macros::hook! {
    unsafe fn pthread_setattr_default_np(
        _attr: *mut libc::c_void
    ) -> libc::c_int => fizzle_pthread_setattr_default_np(ctx) {

        hook_macros::real!(pthread_setattr_default_np)(_attr)
    }
}
    
hook_macros::hook! {
    unsafe fn ptsname(
        _filedes: libc::c_int
    ) -> *mut libc::c_void => fizzle_ptsname(ctx) {

        hook_macros::real!(ptsname)(_filedes)
    }
}
    
hook_macros::hook! {
    unsafe fn ptsname_r(
        _filedes: libc::c_int,
        _buf: *mut libc::c_void,
        _len: libc::size_t
    ) -> libc::c_int => fizzle_ptsname_r(ctx) {

        hook_macros::real!(ptsname_r)(_filedes, _buf, _len)
    }
}
    
hook_macros::hook! {
    unsafe fn putc(
        _c: libc::c_int,
        _stream: *mut libc::c_void
    ) -> libc::c_int => fizzle_putc(ctx) {

        hook_macros::real!(putc)(_c, _stream)
    }
}
    
hook_macros::hook! {
    unsafe fn putc_unlocked(
        _c: libc::c_int,
        _stream: *mut libc::c_void
    ) -> libc::c_int => fizzle_putc_unlocked(ctx) {

        hook_macros::real!(putc_unlocked)(_c, _stream)
    }
}
    
hook_macros::hook! {
    unsafe fn putenv(
        _string: *mut libc::c_void
    ) -> libc::c_int => fizzle_putenv(ctx) {

        hook_macros::real!(putenv)(_string)
    }
}
    
hook_macros::hook! {
    unsafe fn putpwent(
        _p: *mut libc::c_void,
        _stream: *mut libc::c_void
    ) -> libc::c_int => fizzle_putpwent(ctx) {

        hook_macros::real!(putpwent)(_p, _stream)
    }
}
    
hook_macros::hook! {
    unsafe fn pututline(
        _utmp: *mut libc::c_void
    ) -> *mut libc::c_void => fizzle_pututline(ctx) {

        hook_macros::real!(pututline)(_utmp)
    }
}
    
hook_macros::hook! {
    unsafe fn pututxline(
        _utmp: *mut libc::c_void
    ) -> *mut libc::c_void => fizzle_pututxline(ctx) {

        hook_macros::real!(pututxline)(_utmp)
    }
}
    
hook_macros::hook! {
    unsafe fn putw(
        _w: libc::c_int,
        _stream: *mut libc::c_void
    ) -> libc::c_int => fizzle_putw(ctx) {

        hook_macros::real!(putw)(_w, _stream)
    }
}
    
hook_macros::hook! {
    unsafe fn qecvt(
        _value: libc::c_long,
        _ndigit: libc::c_int,
        _decpt: *mut libc::c_void,
        _neg: *mut libc::c_void
    ) -> *mut libc::c_void => fizzle_qecvt(ctx) {

        hook_macros::real!(qecvt)(_value, _ndigit, _decpt, _neg)
    }
}
    
hook_macros::hook! {
    unsafe fn qfcvt(
        _value: libc::c_long,
        _ndigit: libc::c_int,
        _decpt: *mut libc::c_void,
        _neg: *mut libc::c_void
    ) -> *mut libc::c_void => fizzle_qfcvt(ctx) {

        hook_macros::real!(qfcvt)(_value, _ndigit, _decpt, _neg)
    }
}
    
hook_macros::hook! {
    unsafe fn readdir64(
        _dirstream: *mut libc::c_void
    ) -> *mut libc::c_void => fizzle_readdir64(ctx) {

        hook_macros::real!(readdir64)(_dirstream)
    }
}
    
hook_macros::hook! {
    unsafe fn readdir64_r(
        _dirstream: *mut libc::c_void,
        _entry: *mut libc::c_void,
        _result: *mut *mut libc::c_void
    ) -> libc::c_int => fizzle_readdir64_r(ctx) {

        hook_macros::real!(readdir64_r)(_dirstream, _entry, _result)
    }
}
    
hook_macros::hook! {
    unsafe fn readdir_r(
        _dirstream: *mut libc::c_void,
        _entry: *mut libc::c_void,
        _result: *mut *mut libc::c_void
    ) -> libc::c_int => fizzle_readdir_r(ctx) {

        hook_macros::real!(readdir_r)(_dirstream, _entry, _result)
    }
}
    
hook_macros::hook! {
    unsafe fn realloc(
        _ptr: *mut libc::c_void,
        _newsize: libc::size_t
    ) -> *mut libc::c_void => fizzle_realloc(ctx) {

        hook_macros::real!(realloc)(_ptr, _newsize)
    }
}
    
hook_macros::hook! {
    unsafe fn reallocarray(
        _ptr: *mut libc::c_void,
        _nmemb: libc::size_t,
        _size: libc::size_t
    ) -> *mut libc::c_void => fizzle_reallocarray(ctx) {

        hook_macros::real!(reallocarray)(_ptr, _nmemb, _size)
    }
}
    
hook_macros::hook! {
    unsafe fn realpath(
        name: *const libc::c_char,
        resolved: *mut libc::c_char
    ) -> *mut libc::c_char => fizzle_realpath(ctx) {

        crate::strace!("realpath(name={name:?}, resolved={resolved:?}) -> ...");
        let name_cstr = CStr::from_ptr(name);
        let mut res = libc::realpath(name, resolved);

        if name_cstr == c"/var/log/" {
            let ptr = libc::calloc(1, 10).cast::<libc::c_char>();
            std::ptr::copy(name, ptr, 10);
            res = ptr;
        }

        crate::strace!("realpath(name={name_cstr:?}, resolved={resolved:?}) -> {res:?}");
        res
    }
}
    
hook_macros::hook! {
    unsafe fn regcomp(
        _compiled: *mut libc::c_void,
        _pattern: *mut libc::c_void,
        _cflags: libc::c_int
    ) -> libc::c_int => fizzle_regcomp(ctx) {

        hook_macros::real!(regcomp)(_compiled, _pattern, _cflags)
    }
}
    
hook_macros::hook! {
    unsafe fn regerror(
        _errcode: libc::c_int,
        _compiled: *mut libc::c_void,
        _buffer: *mut libc::c_void,
        _length: libc::size_t
    ) -> libc::size_t => fizzle_regerror(ctx) {

        hook_macros::real!(regerror)(_errcode, _compiled, _buffer, _length)
    }
}
    
hook_macros::hook! {
    unsafe fn regfree(
        _compiled: *mut libc::c_void
    ) => fizzle_regfree(ctx) {

        hook_macros::real!(regfree)(_compiled)
    }
}
    
hook_macros::hook! {
    unsafe fn register_printf_function(
        _spec: libc::c_int,
        _handler_function: usize,
        _arginfo_function: usize
    ) -> libc::c_int => fizzle_register_printf_function(ctx) {

        hook_macros::real!(register_printf_function)(_spec, _handler_function, _arginfo_function)
    }
}
    
hook_macros::hook! {
    unsafe fn rewinddir(
        _dirstream: *mut libc::c_void
    ) => fizzle_rewinddir(ctx) {

        hook_macros::real!(rewinddir)(_dirstream)
    }
}
    
hook_macros::hook! {
    unsafe fn rpmatch(
        _response: *mut libc::c_void
    ) -> libc::c_int => fizzle_rpmatch(ctx) {

        hook_macros::real!(rpmatch)(_response)
    }
}
    
hook_macros::hook! {
    unsafe fn scandir(
        dir: *mut libc::c_void,
        namelist: *mut *mut *mut libc::c_void,
        selector: unsafe extern "C" fn(*mut libc::c_void) -> *mut libc::c_void,
        cmp: unsafe extern "C" fn(*mut *mut libc::c_void, *mut *mut libc::c_void) -> *mut libc::c_void
    ) -> libc::c_int => fizzle_scandir(_ctx) {

        hook_macros::real!(scandir)(dir, namelist, selector, cmp)
    }
}
    
hook_macros::hook! {
    unsafe fn scandir64(
        dir: *mut libc::c_void,
        namelist: *mut *mut *mut libc::c_void,
        selector: unsafe extern "C" fn(*mut libc::c_void) -> *mut libc::c_void,
        cmp: unsafe extern "C" fn(*mut *mut libc::c_void, *mut *mut libc::c_void) -> *mut libc::c_void
    ) -> libc::c_int => fizzle_scandir64(ctx) {

        hook_macros::real!(scandir64)(dir, namelist, selector, cmp)
    }
}
    
hook_macros::hook! {
    unsafe fn seekdir(
        _dirstream: *mut libc::c_void,
        _pos: libc::c_long
    ) => fizzle_seekdir(ctx) {

        hook_macros::real!(seekdir)(_dirstream, _pos)
    }
}
    
hook_macros::hook! {
    unsafe fn sem_clockwait(
        _sem: *mut libc::c_void,
        _clockid: libc::clockid_t,
        _abstime: *mut libc::c_void
    ) -> libc::c_int => fizzle_sem_clockwait(ctx) {


        hook_macros::real!(sem_clockwait)(_sem, _clockid, _abstime)
    }
}
    
hook_macros::hook! {
    unsafe fn setcontext(
        _ucp: *mut libc::c_void
    ) -> libc::c_int => fizzle_setcontext(ctx) {


        hook_macros::real!(setcontext)(_ucp)
    }
}
    
hook_macros::hook! {
    unsafe fn setenv(
        _name: *mut libc::c_void,
        _value: *mut libc::c_void,
        _replace: libc::c_int
    ) -> libc::c_int => fizzle_setenv(ctx) {


        hook_macros::real!(setenv)(_name, _value, _replace)
    }
}
    
hook_macros::hook! {
    unsafe fn setfsent() -> libc::c_int => fizzle_setfsent(ctx) {


        hook_macros::real!(setfsent)()
    }
}
    
hook_macros::hook! {
    unsafe fn setgrent() => fizzle_setgrent(ctx) {


        hook_macros::real!(setgrent)()
    }
}
    
hook_macros::hook! {
    unsafe fn setgroups(
        _count: libc::size_t,
        _groups: *mut libc::c_void
    ) -> libc::c_int => fizzle_setgroups(ctx) {


        hook_macros::real!(setgroups)(_count, _groups)
    }
}
    
hook_macros::hook! {
    unsafe fn sethostent(
        _stayopen: libc::c_int
    ) => fizzle_sethostent(ctx) {


        hook_macros::real!(sethostent)(_stayopen)
    }
}
    
hook_macros::hook! {
    unsafe fn sethostid(
        _id: libc::c_long
    ) -> libc::c_int => fizzle_sethostid(ctx) {


        hook_macros::real!(sethostid)(_id)
    }
}
    
hook_macros::hook! {
    unsafe fn setlocale(
        _category: libc::c_int,
        _locale: *mut libc::c_void
    ) -> *mut libc::c_void => fizzle_setlocale(ctx) {


        hook_macros::real!(setlocale)(_category, _locale)
    }
}
    
hook_macros::hook! {
    unsafe fn setlogmask(
        _mask: libc::c_int
    ) -> libc::c_int => fizzle_setlogmask(ctx) {


        hook_macros::real!(setlogmask)(_mask)
    }
}
    
hook_macros::hook! {
    unsafe fn setmntent(
        _file: *mut libc::c_void,
        _mode: *mut libc::c_void
    ) -> *mut libc::c_void => fizzle_setmntent(ctx) {


        hook_macros::real!(setmntent)(_file, _mode)
    }
}
    
hook_macros::hook! {
    unsafe fn setnetent(
        _stayopen: libc::c_int
    ) => fizzle_setnetent(ctx) {


        hook_macros::real!(setnetent)(_stayopen)
    }
}
    
hook_macros::hook! {
    unsafe fn setnetgrent(
        _netgroup: *mut libc::c_void
    ) -> libc::c_int => fizzle_setnetgrent(ctx) {


        hook_macros::real!(setnetgrent)(_netgroup)
    }
}
    
hook_macros::hook! {
    unsafe fn setprotoent(
        _stayopen: libc::c_int
    ) => fizzle_setprotoent(ctx) {


        hook_macros::real!(setprotoent)(_stayopen)
    }
}
    
hook_macros::hook! {
    unsafe fn setpwent() => fizzle_setpwent(ctx) {


        hook_macros::real!(setpwent)()
    }
}
    
hook_macros::hook! {
    unsafe fn setregid(
        _rgid: libc::gid_t,
        _egid: libc::gid_t
    ) -> libc::c_int => fizzle_setregid(ctx) {


        hook_macros::real!(setregid)(_rgid, _egid)
    }
}
    
hook_macros::hook! {
    unsafe fn setreuid(
        _ruid: libc::uid_t,
        _euid: libc::uid_t
    ) -> libc::c_int => fizzle_setreuid(ctx) {


        hook_macros::real!(setreuid)(_ruid, _euid)
    }
}
    
hook_macros::hook! {
    unsafe fn setservent(
        _stayopen: libc::c_int
    ) => fizzle_setservent(ctx) {


        hook_macros::real!(setservent)(_stayopen)
    }
}
    
hook_macros::hook! {
    unsafe fn setstate(
        _state: *mut libc::c_void
    ) -> *mut libc::c_void => fizzle_setstate(ctx) {


        hook_macros::real!(setstate)(_state)
    }
}
    
hook_macros::hook! {
    unsafe fn setutent() => fizzle_setutent(ctx) {


        hook_macros::real!(setutent)()
    }
}
    
hook_macros::hook! {
    unsafe fn setutxent() => fizzle_setutxent(ctx) {


        hook_macros::real!(setutxent)()
    }
}
    
hook_macros::hook! {
    unsafe fn shm_open(
        _name: *mut libc::c_void,
        _oflag: libc::c_int,
        _mode: libc::mode_t
    ) -> libc::c_int => fizzle_shm_open(ctx) {


        hook_macros::real!(shm_open)(_name, _oflag, _mode)
    }
}
    
hook_macros::hook! {
    unsafe fn shm_unlink(
        _name: *mut libc::c_void
    ) -> libc::c_int => fizzle_shm_unlink(ctx) {


        hook_macros::real!(shm_unlink)(_name)
    }
}
    
hook_macros::hook! {
    unsafe fn sigaltstack(
        _stack: *mut libc::c_void,
        _oldstack: *mut libc::c_void
    ) -> libc::c_int => fizzle_sigaltstack(ctx) {


        hook_macros::real!(sigaltstack)(_stack, _oldstack)
    }
}
    
hook_macros::hook! {
    unsafe fn sigblock(
        _mask: libc::c_int
    ) -> libc::c_int => fizzle_sigblock(ctx) {


        hook_macros::real!(sigblock)(_mask)
    }
}
    
hook_macros::hook! {
    unsafe fn siglongjmp(
        _state: *mut libc::c_void,
        _value: libc::c_int
    ) => fizzle_siglongjmp(ctx) {

        hook_macros::real!(siglongjmp)(_state, _value)
    }
}
    
hook_macros::hook! {
    unsafe fn sigpause(
        _mask: libc::c_int
    ) -> libc::c_int => fizzle_sigpause(ctx) {

        hook_macros::real!(sigpause)(_mask)
    }
}
    
hook_macros::hook! {
    unsafe fn sigsetjmp(
        _state: *mut libc::c_void,
        _savesigs: libc::c_int
    ) -> libc::c_int => fizzle_sigsetjmp(ctx) {

        hook_macros::real!(sigsetjmp)(_state, _savesigs)
    }
}
    
hook_macros::hook! {
    unsafe fn sigsetmask(
        _mask: libc::c_int
    ) -> libc::c_int => fizzle_sigsetmask(ctx) {


        hook_macros::real!(sigsetmask)(_mask)
    }
}
    
hook_macros::hook! {
    unsafe fn sigstack(
        _stack: *mut libc::c_void,
        _oldstack: *mut libc::c_void
    ) -> libc::c_int => fizzle_sigstack(ctx) {

        hook_macros::real!(sigstack)(_stack, _oldstack)
    }
}
    
#[unsafe(no_mangle)]
pub unsafe extern "C" fn snprintf(
        s: *mut libc::c_void,
        size: libc::size_t,
        template: *mut libc::c_void,
        mut va_args: ...
    ) -> libc::c_int {
    let res = vsnprintf(s, size, template, va_args);

    let Some(_ctx) = crate::hooks::pre_hook() else {
        return res
    };

    crate::strace!("snprintf({s:?}, {size}, {template:?}, ...) -> ...");

    crate::strace!("snprintf({s:?}, {size}, {template:?}, ...) -> {res}");
    crate::hooks::post_hook();
    res
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn sprintf(
        s: *mut libc::c_void,
        template: *mut libc::c_void,
        mut va_args: ...
    ) -> libc::c_int  {

    let res = vsprintf(s, template, va_args);

    let Some(_ctx) = crate::hooks::pre_hook() else {
        return res
    };

    crate::strace!("sprintf({s:?}, {template:?}, ...) -> ...");

    crate::strace!("sprintf({s:?}, {template:?}, ...) -> {res}");

    crate::hooks::post_hook();
    res
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn sscanf(
        _s: *mut libc::c_void,
        _template: *mut libc::c_void,
        _va_args: ...
    ) -> libc::c_int  {
    let Some(mut ctx) = crate::hooks::pre_hook() else {
        panic!("sscanf() unimplemented for Fizzle internal use");
    };

    todo!("sscanf");
    crate::hooks::post_hook();
}

hook_macros::hook! {
    unsafe fn strcoll(
        _s1: *mut libc::c_void,
        _s2: *mut libc::c_void
    ) -> libc::c_int => fizzle_strcoll(ctx) {

        hook_macros::real!(strcoll)(_s1, _s2)
    }
}
    
hook_macros::hook! {
    unsafe fn strerror(
        _errnum: libc::c_int
    ) -> *mut libc::c_void => fizzle_strerror(ctx) {

        hook_macros::real!(strerror)(_errnum)
    }
}
    
hook_macros::hook! {
    unsafe fn strerror_l(
        _errnum: libc::c_int,
        _locale: libc::locale_t
    ) -> *mut libc::c_void => fizzle_strerror_l(ctx) {

        hook_macros::real!(strerror_l)(_errnum, _locale)
    }
}
    
hook_macros::hook! {
    unsafe fn strerror_r(
        _errnum: libc::c_int,
        _buf: *mut libc::c_void,
        _n: libc::size_t
    ) -> *mut libc::c_void => fizzle_strerror_r(ctx) {

        hook_macros::real!(strerror_r)(_errnum, _buf, _n)
    }
}
    
#[unsafe(no_mangle)]
pub unsafe extern "C" fn strfmon(
        _s: *mut libc::c_void,
        _maxsize: libc::size_t,
        _format: *mut libc::c_void,
        _va_args: ...
    ) -> libc::ssize_t  {
    let Some(mut ctx) = crate::hooks::pre_hook() else {
        panic!("strfmon() unimplemented for Fizzle internal use");
    };

    todo!("strfmon");
    crate::hooks::post_hook();
}

hook_macros::hook! {
    unsafe fn strfroml(
        _string: *mut libc::c_void,
        _size: libc::size_t,
        _format: *mut libc::c_void,
        _value: libc::c_long
    ) -> libc::c_int => fizzle_strfroml(ctx) {

        hook_macros::real!(strfroml)(_string, _size, _format, _value)
    }
}
    
hook_macros::hook! {
    unsafe fn strftime(
        _s: *mut libc::c_void,
        _size: libc::size_t,
        _template: *mut libc::c_void,
        _brokentime: *mut libc::c_void
    ) -> libc::size_t => fizzle_strftime(ctx) {

        hook_macros::real!(strftime)(_s, _size, _template, _brokentime)
    }
}
    
hook_macros::hook! {
    unsafe fn strftime_l(
        _s: *mut libc::c_void,
        _size: libc::size_t,
        _template: *mut libc::c_void,
        _brokentime: *mut libc::c_void,
        _locale: libc::locale_t
    ) -> libc::size_t => fizzle_strftime_l(ctx) {

        hook_macros::real!(strftime_l)(_s, _size, _template, _brokentime, _locale)
    }
}
    
hook_macros::hook! {
    unsafe fn strndup(
        _s: *mut libc::c_void,
        _size: libc::size_t
    ) -> *mut libc::c_void => fizzle_strndup(ctx) {

        hook_macros::real!(strndup)(_s, _size)
    }
}
    
hook_macros::hook! {
    unsafe fn strptime(
        _s: *mut libc::c_void,
        _fmt: *mut libc::c_void,
        _tp: *mut libc::c_void
    ) -> *mut libc::c_void => fizzle_strptime(ctx) {

        hook_macros::real!(strptime)(_s, _fmt, _tp)
    }
}
    
hook_macros::hook! {
    unsafe fn strsignal(
        _signum: libc::c_int
    ) -> *mut libc::c_void => fizzle_strsignal(ctx) {

        hook_macros::real!(strsignal)(_signum)
    }
}
    
hook_macros::hook! {
    unsafe fn strtok(
        _newstring: *mut libc::c_void,
        _delimiters: *mut libc::c_void
    ) -> *mut libc::c_void => fizzle_strtok(ctx) {

        hook_macros::real!(strtok)(_newstring, _delimiters)
    }
}
    
hook_macros::hook! {
    unsafe fn strxfrm(
        _to: *mut libc::c_void,
        _from: *mut libc::c_void,
        _size: libc::size_t
    ) -> libc::size_t => fizzle_strxfrm(ctx) {

        hook_macros::real!(strxfrm)(_to, _from, _size)
    }
}
    
hook_macros::hook! {
    unsafe fn swapcontext(
        _oucp: *mut libc::c_void,
        _ucp: *mut libc::c_void
    ) -> libc::c_int => fizzle_swapcontext(ctx) {

        hook_macros::real!(swapcontext)(_oucp, _ucp)
    }
}
    
#[unsafe(no_mangle)]
pub unsafe extern "C" fn swprintf(
        _ws: *mut libc::c_void,
        _size: libc::size_t,
        _template: *mut libc::c_void,
        _va_args: ...
    ) -> libc::c_int  {
    let Some(mut ctx) = crate::hooks::pre_hook() else {
        panic!("swprintf() unimplemented for Fizzle internal use");
    };

    todo!("swprintf");
    crate::hooks::post_hook();
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn swscanf(
        _ws: *mut libc::c_void,
        _template: *mut libc::c_void,
        _va_args: ...
    ) -> libc::c_int  {
    let Some(mut ctx) = crate::hooks::pre_hook() else {
        panic!("swscanf() unimplemented for Fizzle internal use");
    };

    todo!("swscanf");
    crate::hooks::post_hook();
}

hook_macros::hook! {
    unsafe fn sysconf(
        _parameter: libc::c_int
    ) -> libc::c_long => fizzle_sysconf(ctx) {

        hook_macros::real!(sysconf)(_parameter)
    }
}
    
hook_macros::hook! {
    unsafe fn tcflow(
        _filedes: libc::c_int,
        _action: libc::c_int
    ) -> libc::c_int => fizzle_tcflow(ctx) {

        hook_macros::real!(tcflow)(_filedes, _action)
    }
}
    
hook_macros::hook! {
    unsafe fn tcsendbreak(
        _filedes: libc::c_int,
        _duration: libc::c_int
    ) -> libc::c_int => fizzle_tcsendbreak(ctx) {

        hook_macros::real!(tcsendbreak)(_filedes, _duration)
    }
}
    
hook_macros::hook! {
    unsafe fn tdelete(
        _key: *mut libc::c_void,
        _rootp: *mut *mut libc::c_void,
        _compar: usize
    ) -> *mut libc::c_void => fizzle_tdelete(ctx) {

        hook_macros::real!(tdelete)(_key, _rootp, _compar)
    }
}
    
hook_macros::hook! {
    unsafe fn tdestroy(
        _vroot: *mut libc::c_void,
        _freefct: usize
    ) => fizzle_tdestroy(ctx) {

        hook_macros::real!(tdestroy)(_vroot, _freefct)
    }
}
    
hook_macros::hook! {
    unsafe fn telldir(
        _dirstream: *mut libc::c_void
    ) -> libc::c_long => fizzle_telldir(ctx) {

        hook_macros::real!(telldir)(_dirstream)
    }
}
    
hook_macros::hook! {
    unsafe fn tempnam(
        _dir: *mut libc::c_void,
        _prefix: *mut libc::c_void
    ) -> *mut libc::c_void => fizzle_tempnam(ctx) {

        hook_macros::real!(tempnam)(_dir, _prefix)
    }
}
    
hook_macros::hook! {
    unsafe fn textdomain(
        _domainname: *mut libc::c_void
    ) -> *mut libc::c_void => fizzle_textdomain(ctx) {

        hook_macros::real!(textdomain)(_domainname)
    }
}
    
hook_macros::hook! {
    unsafe fn timegm(
        _brokentime: *mut libc::c_void
    ) -> libc::time_t => fizzle_timegm(ctx) {

        hook_macros::real!(timegm)(_brokentime)
    }
}
    
hook_macros::hook! {
    unsafe fn timelocal(
        _brokentime: *mut libc::c_void
    ) -> libc::time_t => fizzle_timelocal(ctx) {

        hook_macros::real!(timelocal)(_brokentime)
    }
}
    
hook_macros::hook! {
    unsafe fn tmpfile() -> *mut libc::c_void => fizzle_tmpfile(ctx) {

        hook_macros::real!(tmpfile)()
    }
}
    
hook_macros::hook! {
    unsafe fn tmpfile64() -> *mut libc::c_void => fizzle_tmpfile64(ctx) {

        hook_macros::real!(tmpfile64)()
    }
}
    
hook_macros::hook! {
    unsafe fn tmpnam(
        _result: *mut libc::c_void
    ) -> *mut libc::c_void => fizzle_tmpnam(ctx) {

        hook_macros::real!(tmpnam)(_result)
    }
}
    
hook_macros::hook! {
    unsafe fn tsearch(
        _key: *mut libc::c_void,
        _rootp: *mut *mut libc::c_void,
        _compar: usize
    ) -> *mut libc::c_void => fizzle_tsearch(ctx) {

        hook_macros::real!(tsearch)(_key, _rootp, _compar)
    }
}
    
hook_macros::hook! {
    unsafe fn ttyname(
        _filedes: libc::c_int
    ) -> *mut libc::c_void => fizzle_ttyname(ctx) {

        hook_macros::real!(ttyname)(_filedes)
    }
}
    
hook_macros::hook! {
    unsafe fn ttyname_r(
        _filedes: libc::c_int,
        _buf: *mut libc::c_void,
        _len: libc::size_t
    ) -> libc::c_int => fizzle_ttyname_r(ctx) {

        hook_macros::real!(ttyname_r)(_filedes, _buf, _len)
    }
}
    
hook_macros::hook! {
    unsafe fn tzset() => fizzle_tzset(ctx) {

        hook_macros::real!(tzset)()
    }
}
    
hook_macros::hook! {
    unsafe fn unlockpt(
        _filedes: libc::c_int
    ) -> libc::c_int => fizzle_unlockpt(ctx) {

        hook_macros::real!(unlockpt)(_filedes)
    }
}
    
hook_macros::hook! {
    unsafe fn unsetenv(
        _name: *mut libc::c_void
    ) -> libc::c_int => fizzle_unsetenv(ctx) {

        hook_macros::real!(unsetenv)(_name)
    }
}
    
hook_macros::hook! {
    unsafe fn updwtmp(
        _wtmp_file: *mut libc::c_void,
        _utmp: *mut libc::c_void
    ) => fizzle_updwtmp(ctx) {

        hook_macros::real!(updwtmp)(_wtmp_file, _utmp)
    }
}
    
hook_macros::hook! {
    unsafe fn utmpname(
        _file: *mut libc::c_void
    ) -> libc::c_int => fizzle_utmpname(ctx) {

        hook_macros::real!(utmpname)(_file)
    }
}
    
hook_macros::hook! {
    unsafe fn utmpxname(
        _file: *mut libc::c_void
    ) -> libc::c_int => fizzle_utmpxname(ctx) {

        hook_macros::real!(utmpxname)(_file)
    }
}
    
hook_macros::hook! {
    unsafe fn valloc(
        _size: libc::size_t
    ) -> *mut libc::c_void => fizzle_valloc(ctx) {
        
        hook_macros::real!(valloc)(_size)
    }
}
    
#[unsafe(no_mangle)]
pub unsafe extern "C" fn vasprintf(
        ptr: *mut *mut libc::c_void,
        template: *mut libc::c_void,
        ap: std::ffi::VaList
    ) -> libc::c_int  {
    
    let res;
    hook_macros::resolve!(res <= vasprintf(ptr: *mut *mut libc::c_void, template: *mut libc::c_void, ap: std::ffi::VaList) -> libc::c_int);

    let Some(mut ctx) = crate::hooks::pre_hook() else {
        return res
    };

    crate::strace!("vasprintf({ptr:?}, {template:?}, ...) -> ...");

    crate::strace!("vasprintf({ptr:?}, {template:?}, ...) -> {res}");

    crate::hooks::post_hook();
    res
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn verr(
        _status: libc::c_int,
        _format: *mut libc::c_void,
        _ap: std::ffi::VaList
    )  {
    let Some(mut ctx) = crate::hooks::pre_hook() else {
        panic!("verr() unimplemented for Fizzle internal use");
    };

    todo!("verr");
    crate::hooks::post_hook();
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn verrx(
        _status: libc::c_int,
        _format: *mut libc::c_void,
        _ap: std::ffi::VaList
    )  {
    let Some(mut ctx) = crate::hooks::pre_hook() else {
        panic!("verrx() unimplemented for Fizzle internal use");
    };

    todo!("verrx");
    crate::hooks::post_hook();
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn vfwscanf(
        stream: *mut libc::c_void,
        template: *mut libc::c_void,
        ap: std::ffi::VaList
    ) -> libc::c_int  {

    let res;
    hook_macros::resolve!(res <= vfwscanf(stream: *mut libc::c_void, template: *mut libc::c_void, ap: std::ffi::VaList) -> libc::c_int);

    let Some(_ctx) = crate::hooks::pre_hook() else {
        return res
    };

    crate::strace!("vfwscanf(stream={stream:?}, template={template:?}, ...) -> ...");

    crate::strace!("vfwscanf(stream={stream:?}, template={template:?}, ...) -> {res}");
    crate::hooks::post_hook();
    res
}

hook_macros::hook! {
    unsafe fn vlimit(
        resource: libc::c_int,
        limit: libc::c_int
    ) -> libc::c_int => fizzle_vlimit(_ctx) {

        hook_macros::real!(vlimit)(resource, limit)
    }
}
    
#[unsafe(no_mangle)]
pub unsafe extern "C" fn vsnprintf(
        s: *mut libc::c_void,
        size: libc::size_t,
        template: *mut libc::c_void,
        ap: std::ffi::VaList
    ) -> libc::c_int  {
    let res;
    hook_macros::resolve!(res <= vsnprintf(s: *mut libc::c_void, size: libc::size_t, template: *mut libc::c_void, ap: std::ffi::VaList) -> libc::c_int);

    let Some(_ctx) = crate::hooks::pre_hook() else {
        return res
    };

    crate::strace!("vsnprintf(s={s:?}, size={size}, template={template:?}, ...) -> ...");

    crate::strace!("vsnprintf(s={s:?}, size={size}, template={template:?}, ...) -> {res}");
    crate::hooks::post_hook();
    res
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn vsprintf(
        s: *mut libc::c_void,
        template: *mut libc::c_void,
        ap: std::ffi::VaList
    ) -> libc::c_int  {

    let res;
    hook_macros::resolve!(res <= vsprintf(s: *mut libc::c_void, template: *mut libc::c_void, ap: std::ffi::VaList) -> libc::c_int);

    let Some(_ctx) = crate::hooks::pre_hook() else {
        return res
    };

    crate::strace!("vsprintf(s={s:?}, template={template:?}, ...) -> ...");

    crate::strace!("vsprintf(s={s:?}, template={template:?}, ...) -> {res}");
    crate::hooks::post_hook();
    res
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn vsscanf(
        s: *mut libc::c_void,
        template: *mut libc::c_void,
        ap: std::ffi::VaList
    ) -> libc::c_int  {

    let res;
    hook_macros::resolve!(res <= vsscanf(s: *mut libc::c_void, template: *mut libc::c_void, ap: std::ffi::VaList) -> libc::c_int);

    let Some(_ctx) = crate::hooks::pre_hook() else {
        return res
    };


    crate::hooks::post_hook();
    res
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn vswprintf(
        ws: *mut libc::c_void,
        size: libc::size_t,
        template: *mut libc::c_void,
        ap: std::ffi::VaList
    ) -> libc::c_int  {
    let res;
    hook_macros::resolve!(res <= vswprintf(ws: *mut libc::c_void, size: libc::size_t, template: *mut libc::c_void, ap: std::ffi::VaList) -> libc::c_int);

    let Some(_ctx) = crate::hooks::pre_hook() else {
        return res
    };

    crate::strace!("vswprintf(ws={ws:?}, size={size}, template={template:?}, ...) -> ...");

    crate::strace!("vswprintf(ws={ws:?}, size={size}, template={template:?}, ...) -> {res}");
    crate::hooks::post_hook();
    res
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn vswscanf(
        _s: *mut libc::c_void,
        _template: *mut libc::c_void,
        _ap: std::ffi::VaList
    ) -> libc::c_int  {
    let Some(mut ctx) = crate::hooks::pre_hook() else {
        panic!("vswscanf() unimplemented for Fizzle internal use");
    };

    todo!("vswscanf");

    crate::hooks::post_hook();
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn vwarn(
        _format: *mut libc::c_void,
        _ap: std::ffi::VaList
    )  {
    let Some(mut ctx) = crate::hooks::pre_hook() else {
        panic!("vwarn() unimplemented for Fizzle internal use");
    };

    todo!("vwarn");

    crate::hooks::post_hook();
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn vwarnx(
        _format: *mut libc::c_void,
        _ap: std::ffi::VaList
    )  {
    let Some(mut ctx) = crate::hooks::pre_hook() else {
        panic!("vwarnx() unimplemented for Fizzle internal use");
    };

    todo!("vwarnx");

    crate::hooks::post_hook();
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn vwscanf(
        _template: *mut libc::c_void,
        _ap: std::ffi::VaList
    ) -> libc::c_int  {
    let Some(mut ctx) = crate::hooks::pre_hook() else {
        panic!("vwscanf() unimplemented for Fizzle internal use");
    };

    todo!("vwscanf");

    crate::hooks::post_hook();
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn warn(
        _format: *mut libc::c_void,
        _va_args: ...
    )  {
    let Some(mut ctx) = crate::hooks::pre_hook() else {
        panic!("warn() unimplemented for Fizzle internal use");
    };

    todo!("warn");

    crate::hooks::post_hook();
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn warnx(
        _format: *mut libc::c_void,
        _va_args: ...
    )  {
    let Some(mut ctx) = crate::hooks::pre_hook() else {
        panic!("warnx() unimplemented for Fizzle internal use");
    };

    todo!("warnx");

    crate::hooks::post_hook();
}

hook_macros::hook! {
    unsafe fn wcrtomb(
        _s: *mut libc::c_void,
        _wc: libc::wchar_t,
        _ps: *mut libc::c_void
    ) -> libc::size_t => fizzle_wcrtomb(ctx) {

        hook_macros::real!(wcrtomb)(_s, _wc, _ps)
    }
}
    
hook_macros::hook! {
    unsafe fn wcscoll(
        _ws1: *mut libc::c_void,
        _ws2: *mut libc::c_void
    ) -> libc::c_int => fizzle_wcscoll(ctx) {

        hook_macros::real!(wcscoll)(_ws1, _ws2)
    }
}
    
hook_macros::hook! {
    unsafe fn wcsdup(
        _ws: *mut libc::c_void
    ) -> *mut libc::c_void => fizzle_wcsdup(ctx) {

        hook_macros::real!(wcsdup)(_ws)
    }
}
    
hook_macros::hook! {
    unsafe fn wcsftime(
        _s: *mut libc::c_void,
        _size: libc::size_t,
        _template: *mut libc::c_void,
        _brokentime: *mut libc::c_void
    ) -> libc::size_t => fizzle_wcsftime(ctx) {

        hook_macros::real!(wcsftime)(_s, _size, _template, _brokentime)
    }
}
    
hook_macros::hook! {
    unsafe fn wcsnrtombs(
        _dst: *mut libc::c_void,
        _src: *mut *mut libc::c_void,
        _nwc: libc::size_t,
        _len: libc::size_t,
        _ps: *mut libc::c_void
    ) -> libc::size_t => fizzle_wcsnrtombs(ctx) {

        hook_macros::real!(wcsnrtombs)(_dst, _src, _nwc, _len, _ps)
    }
}
    
hook_macros::hook! {
    unsafe fn wcsrtombs(
        _dst: *mut libc::c_void,
        _src: *mut *mut libc::c_void,
        _len: libc::size_t,
        _ps: *mut libc::c_void
    ) -> libc::size_t => fizzle_wcsrtombs(ctx) {

        hook_macros::real!(wcsrtombs)(_dst, _src, _len, _ps)
    }
}
    
hook_macros::hook! {
    unsafe fn wcstombs(
        _string: *mut libc::c_void,
        _wstring: *mut libc::c_void,
        _size: libc::size_t
    ) -> libc::size_t => fizzle_wcstombs(ctx) {

        hook_macros::real!(wcstombs)(_string, _wstring, _size)
    }
}
    
hook_macros::hook! {
    unsafe fn wcsxfrm(
        _wto: *mut libc::c_void,
        _wfrom: *mut libc::c_void,
        _size: libc::size_t
    ) -> libc::size_t => fizzle_wcsxfrm(ctx) {

        hook_macros::real!(wcsxfrm)(_wto, _wfrom, _size)
    }
}
    
hook_macros::hook! {
    unsafe fn wctomb(
        _string: *mut libc::c_void,
        _wchar: libc::wchar_t
    ) -> libc::c_int => fizzle_wctomb(ctx) {

        hook_macros::real!(wctomb)(_string, _wchar)
    }
}
    
hook_macros::hook! {
    unsafe fn wordexp(
        _words: *mut libc::c_void,
        _word_vector_ptr: *mut libc::c_void,
        _flags: libc::c_int
    ) -> libc::c_int => fizzle_wordexp(ctx) {

        hook_macros::real!(wordexp)(_words, _word_vector_ptr, _flags)
    }
}
    
hook_macros::hook! {
    unsafe fn wordfree(
        _word_vector_ptr: *mut libc::c_void
    ) => fizzle_wordfree(ctx) {

        hook_macros::real!(wordfree)(_word_vector_ptr)
    }
}
    
#[unsafe(no_mangle)]
pub unsafe extern "C" fn wscanf(
        _template: *mut libc::c_void,
        _va_args: ...
    ) -> libc::c_int  {
    let Some(mut ctx) = crate::hooks::pre_hook() else {
        panic!("wscanf() unimplemented for Fizzle internal use");
    };

    todo!("wscanf");

    crate::hooks::post_hook();
}
